pwa-builder/PWABuilder

app/templates/documentation.hbs
Myself and a few others from the Microsoft Edge team spent a couple days last week creating a Hosted Windows App and packaging it with ManifoldJS. 
ManifoldJS is a great tool to help us accomplish this, but we felt that in the example commands the `manifoldjs run ...` command should be called out in the example documentation. It's an immensely helpful command for debugging locally and we ran into MANY issues trying to replicate that command manually before realizing that ManifoldJS did that magic for us.
=> Add running a windows 10 app locally example to documentation.

Brocfile.js, app/components/generator-step.js, bower.json
When the user navigates to /generator the component generator-step is adding the step to steps list, to avoid duplicates before add the steps the component is checking if the current steps exists.
=> Bugfix generator step

pages/_lang/generate.vue
After reviewing the production site, I found out that the displayed manifest is generated with two issues: 
o	Between the property quotation marks and the colon, the application adds an extra semicolon.
o	The use of apostrophes on the icons properties instead of quotation marks.
I fixed both issues with this branch.
=> Fixed manifest issues on "generate manifest" page.

components/GeneratorMenu.vue
This removes build error (at least on my fresh install):
```bash
ERROR in 
components/GeneratorMenu.vue
2:1  ✖  Expected no more than 1 empty line   max-empty-lines
```
Thanks!
=> Fix max-empty-lines error during compilation

components/CodeViewer.vue, layouts/default.vue, pages/_lang/reportCard.vue, store/modules/generator/generator.actions.ts, store/modules/publish.ts, store/modules/windows/windows.actions.ts, test/store/modules/generator/generator.helpers.test.ts, test/utils/action-context.mock.ts, tsconfig.json, tslint.json
This is a proposal to correct/silence some noise in the `redesign` branch:
- migrate configuration
- work with compilation errors by removing unused variables,
silencing warnings for unused arguments with `_` notation or
TSIgnore pragma
When run in 'redesign' branch the current setup results in `no-unused-variables` warning and its migration warning or, when moved to TS:
```txt
ERROR in /Users/piotrblazejewicz/git/PWABuilder/components/CodeViewer.vue(136,17):
TS6133: 'copy' is declared but its value is never read.
ERROR in /Users/piotrblazejewicz/git/PWABuilder/components/CodeViewer.vue(163,11):
TS6133: 'showErrorOverlay' is declared but its value is never read.
ERROR in /Users/piotrblazejewicz/git/PWABuilder/components/CodeViewer.vue(167,11):
TS6133: 'closeOverlay' is declared but its …
```
=> Migrate no-unused-variable TSLint to TS configuration rules

tsconfig.json
The directory content is directly imported via require in Nuxt
configuration files. Without this change the content of the directory is
supposed to be compiled via `allowJs` flag, which results in error about
overriding input files.
Thanks!
```text
Cannot write file '/{...}/PWABuilder/environments/development.js' because it would overwrite input file.
```
=> Exclude environments directory from TS compilation

components/GeneratorMenu.vue, pages/_lang/windows.vue, store/modules/generator/generator.actions.ts
~~when the TypeScript version installs with >2.9, the TSLint starts spilling warning about `no-unused-variables` deprecation. This commit tries to clean the output during build steps:~~
~~- update linter configuration~~
~~- add rules to TS configuration~~
~~- remove variable when not used and not referenced and not required by
contract~~
~~- prefix unused params with _ when applicable (this removes compiler
warning)~~
~~- add @ts-ignore pragma where applicable~~
**Edited after rebasing to onto current redesign branch**
Fix linting and compile time errors
- fix max-empty-lines linting error
- add @ts-ignore pragma where applicable to fix TS6133
Thanks!
Thanks!
=> Fix `no-unused-variables` and `max-empty-lines` linting errors [EDITED]

layouts/default.vue
Cookie Banner was covering site identity, so if user redirected to site, they don't have clear visual on who is asking about cookies.  Better to have both site identity and the request/ask about cookies visible together:
This fix also removes a redundant sass block.
=> Make Cookie Banner Push Content Down

pages/_lang/generate.vue
Bugfix
There was a typo in the description of the `Display` property for the manifest settings.
Fixed the typo
=> Fixing typo in description of the Display manifest property

pages/_lang/generate.vue
Fixes #624 
Bugfix
We currently recommend users use the .webmanifest extension for their web manifest. This PR changes that wording to the more common .json extension. This actually lines us up more with what gets generated by the web platform still anyways https://github.com/pwa-builder/pwabuilder-web/blob/1e6dc4c396561796d1eba22b9baeead5bbd7099d/lib/platform.js#L53
=> chore(): change back to .json instead of .webmanifest

components/Download.vue
- Bugfix
llama-pack/bubblewrap throws the following error: `twaManifest.shortcuts.map is not a function`
This is because the shortcuts property is passed as a string (`"[]"`) and not as an actual array.
We’re now passing in an actual array.
N/A
=> fix(download): shortcuts must be a real array

pages/_lang/feature/_detail.vue, store/modules/windows/windows.actions.ts
Better layout for Feature Store doc
Removing older unused component: Geoloc, Adaptive card and copy clipboard
=> Better layout for Feature Store

pages/_lang/feature/_detail.vue
Avoid getting a white page when using uBlock (awa is undefined).
=> Fix feature/_detail.vue with uBlock

components/Download.vue, components/HubHeader.vue, pages/_lang/feature/_detail.vue, pages/_lang/features.vue, pages/_lang/generate.vue, pages/_lang/publish.vue, pages/_lang/reportCard.vue, pages/_lang/serviceworker.vue
Fixes #719 .
This fix makes sure awa is defined before trying to send analytics data. This makes sure that we dont break / populate the console with errors for Safari users + users with aggressive blocking extensions.
=> fix(): make sure awa is defined before sending

components/CodeViewer.vue, pages/_lang/generate.vue, utils/helper.ts
Fixes #
1)  edits in manifest should reflect in form and not reset [#560](https://github.com/pwa-builder/PWABuilder/issues/560)
2)  if I edit the manifest, then click back on the form, my work goes away [#564](https://github.com/pwa-builder/PWABuilder/issues/564)
=> Edits in manifest reflect in form

store/modules/generator/generator.helpers.ts, uitest/index.spec.js
Fixes #
https://github.com/pwa-builder/PWABuilder/issues/731
Bugfix
It doesn't check if the additional path on the manifest is also included on the icons url
It will remove the additional path if it exist on both icons and manifest to avoid it being duplicated
Tests were failing on the github action (they pass on local) but it doesn't seem related to my change. I added a possible fix but I can remove it if necessary
=> Fix duplication of path on icons

layouts/default.vue, pages/_lang/reportCard.vue
Fixes #
issue #755 
- Bugfix
Current behavior breaks a mobile breakpoint larger than 425px.
Using the fluent design breakpoints to set the max-width of certain properties to behave as expected on mobile (640px), talk about size creep.
This does not include phablets which are considered to be in the same category as small laptops and tablets.
https://docs.microsoft.com/en-us/windows/uwp/design/layout/screen-sizes-and-breakpoints-for-responsive-design
Use of fluent and UWP design to make the decision. Better org alignment?
=> Address #755, hide the download card on mobile, fix gdpr notification height for mobile breakpoints

assets/SnippitPop.ts
SnippetPop is now TypeScript, which fixes a compiler warning about using input files as output.
=> SnippitPop is now TS, fixing compiler warning

components/CodeViewer.vue
Fixes #
Found
- Bugfix
The reference was stale and referring to an editor that is removed from the dom.
On resize captures the new editor.
Not high pri, just something I noticed while I was trying to replicate the wrapped component
=> reference recreated monaco ref, editor holding stale ref

pages/_lang/reportCard.vue
Fixes #
https://github.com/pwa-builder/PWABuilder/issues/810
Currently, a screen reader does not indicate that the Get Started button leads to a popup of buttons.
When navigating to the Get Started button, the screen reader indicates that the Get Started button has a popup.
=> Accessibility Issue Fix: Added accessibility labels to the Get Started dropdown

pages/_lang/reportCard.vue
Fixes 
https://github.com/pwa-builder/PWABuilder/issues/817
Currently, after pressing the "Clone from Github" button, a visual message appears: “Git clone command copied to your clipboard”. However, a screen reader does not voice this alert. 
The “Git clone command copied to your clipboard” message is read aloud by a screen reader.
=> Accessibility Issue Fix: Add alert for “Git clone command copied to your clipboard”

components/HubHeader.vue
Fixes #833 
Bugfix 
The span elements inside the anchor tag get focused by the screen-reader, but to a screen reader those elements have no use. 
Using aria-hidden to hide these "unactivateable" elements from the screen reader
=> fix(): hide spans from screen readers

components/Modal.vue
Fixes
https://github.com/pwa-builder/PWABuilder/issues/842
Currently, a screen reader only reads the close button for the "Upload an Image" modal view as "button".
Now, the screen reader reads the close button for the "Upload an Image" modal view as "close button".
=> Accessibility Issue Fix: Added aria-label for close button

pages/_lang/reportCard.vue
Fixes 
https://github.com/pwa-builder/PWABuilder/issues/847
Focus is not visible for the "Start" and "Get Started" buttons
Focus is now visible for the "Start" and "Get Started" buttons
=> Accessibility Issue Fix: Added keyboard focus for Start and Get Started buttons

pages/_lang/reportCard.vue
Fixes
https://github.com/pwa-builder/PWABuilder/issues/831
Keyboard focus does not get visible on 'Share your results' button present on the page.
Keyboard focus is now visible for the 'Share your results' button.
=> Accessibility Issue Fix: Added keyboard focus on Share Your Results button

components/ScoreCard.vue
Fixes 
https://github.com/pwa-builder/PWABuilder/issues/832
Separate 'Tab' focus is moving to the "app manifest" link after pressing 'Tab' from "Couldn't find an app manifest" link.
Only "Couldn't find an app manifest" is focused on by a screen reader. "app manifest" is not focused on its own.
=> Accessibility Issue Fix: Set tabindex of app manifest link to -1 for screen reader logic

assets/scss/base/_globals.scss
Fixes #
#864 
- Bugfix
Globally all button's focus states are removed.
Outline state works as intended.
=> outline fix

components/HubHeader.vue
Fixes #
#896 
- Bugfix
The header steals focus before moving onto other buttons.
The header behaves as a container.
=> adding tag

components/ScoreCard.vue
Fixes #953 by hiding the push notification score. We may change this in near future as the new score page is under design.
=> Hiding service worker score

layouts/default.vue
Fixes #915 
- Bugfix
Dev build versions of edge seem to focus on the empty divs with narrator.
Marking the divs as role="presentation" to allow their content to be focuseable, but themselves not to be
=> Issue 915 pt 2

pages/_lang/reportCard.vue
Fixes #833 
Bugfix
In edge cases where the URL the user lands on is something like this `https://preview.pwabuilder.com/?url` the site used to continue forward like there was a valid URL. This happened because, even though the URL was undefined, decodeURIComponent was returning undefined as a string, this case is now handled. URLs such as these should not be landed on during normal use of the app, but as we have seen with  the linked issue there are edge cases.
The case described above is handled.
- [ x] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility …
=> fix(): handle edge case for location.search

components/ScoreCard.vue
Fixes 
After the move to our latest tests, the experience during the loading portion of the tests was a little wonky. For example, while the security test was running in the background, the security card showed as if the test returned broken for a minute until the test loaded. The manifest test also had a similar issue with when the score showed up. This PR fixes this and makes the loading experience the same as before. This also has some formatting fixes.
=> fix(): improve loading experience of tests

components/ScoreCard.vue
- Bugfix
When a manifest is not found, the manifest.generated check in the mutation causes an exception.
Thought the finally clause would be skipped with a return statement in the catch block.
Do not trigger the manifest mutation (not needed here anyway) when the manifest is null.
=> no manifest found causes issue in finally clause

components/Modal.vue, pages/_lang/publish.vue
Fixes #1051
- Bugfix
The focus after an update would shift on modal nested components back to the close button.
Changes focus only on the updates that show the modal (showModal), added a bool to ensure it happens only once, and on close resets the state to happen on opening of the modal again.
=> Issue 1051

pages/_lang/reportCard.vue
Fixes #868
- Bugfix
The test spacing throws off the height of lines which causes the collision between the absolutely positioned element and the card block.
The issue underlying is the absolute positioning of the terms text, just switching that off for certain view heights, also there's a scroll issue with the grid at the scale so removing it for better flow. Scroll fixed.
=> Issue868 try 2

pages/_lang/reportCard.vue
Fixes #821 
- Bugfix
Contrast between element background and text wasn't enough with a transparent background (for the teal part).
Added a purple transparent background to help with the contrast ratio. Styled to make it look round. Please let me know if there's another style I should go for.
=> url input contrast ratio

pages/_lang/generate.vue
Fixes #1066 
Bugfix
Layout is broken after navigating to the manifest editor and back.
The issue was that we had an id called "main" in both the reportCard and generator pages. Because of that, when you navigated to the generator page the browser loaded that css which meant that when you navigated back that new css on `#main` was overriding. When we move to a web components-based solution in the future (far future haha) we won't have issues like this because of shadow dom.
- [ x] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design). Use tools like …
=> fix(): fixes #1066

pages/_lang/publish.vue
Fixes #1083, graceful handling when theme color is missing from manifest.
=> Fixed #1083, handling of missing nav color

components/ScoreCard.vue
We show loading "skeleton screens" for each card while the tests are running. This does not effectively communicate to the user WHAT is going on, only that something is going on. 
This update aims to fix that with the following UI update:
The loading icon and the text that you see in the manifest card here is also shown for our main long running test, the service worker one. In this screenshot it just happened to finish before the manifest test.
- [x ] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/ …
=> fix(): improve loading experience of cards

components/ScoreCard.vue, pages/_lang/reportCard.vue, store/modules/generator/generator.actions.ts, store/modules/generator/generator.state.ts, utils/manifest-fetcher.ts
Fixes #976 
In this PR, we:
- Run the manifest detectors simultaneously and use whatever result completes successfully
- Send the manifest contents to API v2, so as to avoid repeat errors when analyzing the manifest, and to speed up analysis by skipping having to fetch it again.
The last point above will fully work once the API v2 has been updated to accept the POST'd manifest.
=> Sending manifest contents to API

components/ScoreCard.vue
Sends manifest URL along with manifest body in POST call to manifest analysis API. Makes the front-end conform to this PR: https://github.com/pwa-builder/pwabuilder-api-v2/pull/23
=> Added manifest URL to POST body for analysis

components/Download.vue, pages/_lang/publish.vue
Feature 
Adds a new button to allow the user to still download a legacy edge package if they want. This works the exact same way as the legacy android webview button works.
=> feat(): add legacy edge button

components/ScoreCard.vue
Bugfix
When in the cached flow, we were not getting the manifest into the redux flow. Because of that, when you went to package with the new Windows or Android platforms, they would fail because the manifest (which they get from the redux state) was not in the redux state.
This updates the cached flow to still make the call that puts the manifest into the redux flow.
=> fix(): caching workflow redux fix

components/CodeViewer.vue, pages/_lang/publish.vue, utils/android-utils.ts
Implements #1159, hiding non-required signing options when signing mode = "new"
=> Android options hiding non required options

pages/_lang/reportCard.vue
Bugfix
The site had the wrong padding/margin between 542px and 800px:
Has the correct amount of padding on all sizes.
=> fix(): site now has correct amount of padding and margin

pages/_lang/reportCard.vue
Fixes
https://github.com/pwa-builder/PWABuilder/issues/821
- Accessibility text change, removed left over relative positioning code from an earlier revision that I've changed to flex at breaks points since.
- Color contrast wasn't high enough on mentioned lower text.
- brought it up
=> lower text color contrast text

components/FeatureCard.vue
aria-label for these cards... no indication of how to get here from poster.
Fixes #823 
- Bugfix
- descriptive aria label missing
- Adds aria label to element
=> Issue #823 in PWABuilder not pwa-features

assets/scss/base/_globals.scss, components/CodeViewer.vue
Fixes #854 
- Bugfix
- the color contrast wasn't high enough
- Add more color contrast
=> Issue 854 - force color change, opacity change by 20%

pages/_lang/publish.vue
Fixes #1201 Image selection for Windows and Android platforms handles gracefully the case where image types aren't specified in a PWA's web manifest.
=> Fallback image when no image types specified

pages/_lang/publish.vue, store/modules/generator/generator.helpers.ts
Manifest icon paths are transformed to absolute paths correctly
=> Fixes #1211, relative paths of icons in manifest

pages/_lang/reportCard.vue
Fixes #
Fixes an issue I saw when Melanie was demoing Friday where the route that we pushed to after a download of the starter was an old route that did not exist anymore. This section is going to be rebuilt / redesigned with PWABuilder 3.0, but just wanted to do a patch fix for now for this bug.
Bugfix
No more re-routing of the user after they have downloaded the starter.
=> fix(): remove old route push

pages/_lang/publish.vue
Addresses issue where finding a suitable icon would return a non-square icon if it was larger than the required size. Suitable icon now takes into account squareness of the desired icon.
=> Suitable icon matches account for squareness

components/ScoreCard.vue, store/modules/generator/generator.helpers.ts
Fixes #1224 where image paths weren't resolved to absolute correctly. Fixed by removing old pathing code, opting now instead for what the browser does: constructing a URL with a path relative to the manifest.
=> #1224 Fixing icon paths

pages/_lang/publish.vue
Makes the new Chromium-based Edge platform the primary Windows download, moves the legacy EdgeHTML platform to the footer.
=> New Edge platform as primary

pages/_lang/generate.vue
Fixes #1234 #216 #726 
- Bugfix
- Refactor
The service was down.
Service is back up, and fixed a CORS issue by migrating to fetch.
=> Zip All functionality move from axios to fetch

components/Download.vue, environments/development.js, environments/preview.js, environments/production.js, environments/test.js
Fixes #1314, #1313, #1312, #1299, #1266
In particular, if the Android tools is blocked from accessing an image or manifest, we try again using a URL proxy.
=> Added safe URL fetching fallback

utils/android-utils.ts
Fixes #1336, removes leading digits from a package ID segment
=> Fix for #1336

src/script/components/app-header.ts, src/script/components/content-header.ts, src/script/pages/app-home.ts
I was using raw media queries.
This PR updates my CSS to use Leo's new utils.
=> refactor(): use css utils instead of raw media queries

.vscode/extensions.json, .vscode/launch.json, .vscode/tasks.json, README.md, package-lock.json, package.json, rollup.config.dev.js, rollup.config.js, tsconfig.dev.json, web-dev-server.config.mjs, web-dev-server.debugging.config.mjs
Specifically, we've added TypeScript debugging to both Dev Tools and VS Code.
Our dev build now outputs source maps, enabling you to debug TypeScript in F12 Dev Tools.
Additionally, I've added debugging capabilities for VS Code. To debug in VS Code, install the [Debugger for Microsoft Edge extension](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-edge), add a breakpoint in a TypeScript file in VS Code, then hit F5 to debug.
I've updated the project's readme with this information. 
I've also updated the VS Code recommended extensions for this project.
=> Added VSCode F5 debugging

components/Download.vue
Fixes #1365 by expanding the conditions in which we retry a failed Android build using the safe URL service.
=> Fixes #1365

src/script/components/app-button.ts, src/script/components/loading-button.ts, src/script/components/resource-hub.ts, src/script/pages/app-home.ts
We have our CSS variables standardized for our buttons, but for the main style of button throughout the site you still needed to make sure you add the right CSS vars. This PR wraps fast-button in an app-component button that has these styles by default so that things are even more standardized across the UI.
This PR also goes ahead and refactors to use this button where the standard button design is used.
- [ x] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design). Use tools like …
=> refactor(): add app-button component

src/script/components/app-alert.ts, src/script/pages/app-about.ts
Feature
New alert component, can be tested on the about page. This component works very similarly to app-modal in the fact that its content all comes from slots and therefore is fully customizable. However, this component differs from app-modal in the fact that it is controlled through an exposed JS API from the component, not just props. The reason for this is because the alert is meant to open where the user clicked (like the right click dialogue) so I need to do things in JS for that to happen.
- [ x] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility …
=> feat(): new app-alert component

package-lock.json, pages/_lang/publish.vue, store/modules/publish.ts
- Adds support for package language (https://github.com/pwa-builder/pwabuilder-windows-chromium-docs/issues/4).
- Adds support for overriding the PWA's start URL in response to partner requirement.
=> Additional windows platform fields

static/manifest.webmanifest
Application pane in Chrome Canary DevTools raises a warning with pwabuilder.com web manifest as you can see below. This PR fixes it by renaming `size` to `sizes` [screenshots property](https://developer.mozilla.org/en-US/docs/Web/Manifest/screenshots).
=> Fix typo in web app manifest screenshot file

src/script/components/report-card.ts, src/script/pages/app-publish.ts
Bugfix
The report card was rendering without results, which should never happen.
This PR makes the report data mandatory for the report-card component + adds a fallback to grab the last saved results if the component attempts to render without results (which should not happen anymore with this fix, but I wanted a fallback anyways).
=> fix(): small bug with reports + add fallback

src/script/pages/app-testing.ts, src/script/services/tests/index.ts, src/script/services/tests/manifest.ts, src/script/services/tests/service-worker.ts
Bugfix
Sites that did not have a service worker were stalling out on the testing page. Turns out this was caused by some pre-mature throwing of errors that was breaking promise chains.
=> fix(): non-pwa site does not stall on testing page

src/script/components/app-header.ts, src/script/components/score-results.ts, src/script/pages/app-home.ts, src/script/pages/app-publish.ts, src/script/pages/app-testing.ts, src/script/services/manifest.ts, src/script/services/publish/android-publish.ts, src/script/services/publish/windows-publish.ts, src/script/services/tests/manifest.ts, src/script/utils/interfaces.ts
Bugfix
This PR does the following small fixes / tweaks / cleanup chores:
- removes the testing modal that was on the home page. This was there originally as an example of how to use the component, but is not needed now.
- Sites with no manifest are now scored correctly. We were scoring based off the manifest we generated for a site instead of the actual manifest or lack of manifest.
- Correct URL is used for publishing + download is now a separate button (which we had already discussed in design syncs) which fixes an issue where the file access API can only be used from a user gesture. This also required some minor refactoring to the Windows and Android generation logic.
- Added a missing import
- The testing page now has the latest …
=> General fixes and cleanup

src/script/components/app-header.ts, src/script/pages/app-home.ts, src/script/pages/app-testing.ts
Feature
This PR adds the following:
- the icon in the header acts as a back button just like on the current production site
- Added a bottom border to the header to match the latest design
- Dont show border on the header on the testing page
=> feat(): header img goes back + header border to match design

src/script/services/publish/android-publish.ts
Fixes Android platform download by resolving relative URLs.
In the old site, these URLs were absolute-ified inside the state manager after fetching the manifest.
=> URL resolution for Android platform

pages/_lang/publish.vue
Fixes #1546, changes the info text for Android signing options to the modern recommendations.
=> Fixes #1546

src/script/components/app-card.ts, src/script/components/blog-showcase.ts, src/script/components/resource-hub.ts, src/script/pages/app-congrats.ts
- Feature
- use resource hub for the links to places such as demos and components, and etc.
- going to breakout the blog-showcase component into css as the logic changes make it simpler to just keep the loops within the complete page.
app-card
- use class rather than mode
- technically can mix and match classes...
- ids to classes
resource-hub
- publish -> complete
- some refactor, put in-line with experience learned from manifest page
- simplify and split up css sub functions (makes next step easier).
- ids to classes
- modularize the structural CSS from the blog-showcase component which I designed for the complete page. With the change to the implementation being custom, makes more sense to keep the structural logic in the complete page rather than split it off into its own component.
=> V3 - complete page use resource hub.

src/script/components/resource-hub.ts
Fixes #
Bugfix
There was a red background being applied to the resource-hub that is not in the design. 
Removed the red background so that it matches the design.
=> fix(): remove red background on cards

src/script/components/content-header.ts
Fixes #
Bugfix 
Surface duo sized devices had styles that were not quite right, and therefore in a browser with the tab bar up top, the UI was a little "squished".
This PR tweaks heights and adds a little more margin top to fix this problem.
=> fix(): bit more margin-top on duo sized devices

src/script/components/windows-form.ts
Bugfix
The start_url field in the windows form was showing undefined by default instead of the actual start_url from the users manifest.
Correct start_url is now used.
=> fix(): start_url, not startUrl

components/ManifestScoreCard.vue
- Bugfix
Jut a quick PR, The current link is broken since the content has been moved to a new URL.
The new URL is https://www.w3.org/TR/manifest-app-info/#iarc_rating_id-member
=> Update link to IARC rating ID

utils/service-worker-checker.ts
Fix for #1597, specifically the [offline check failing intermittently](https://github.com/pwa-builder/PWABuilder/issues/1597#issuecomment-824444172) for https://flashmath.cards
=> Added offline check fallback

package-lock.json, src/script/components/loading-button.ts, src/script/pages/app-home.ts
Fixes #
We had moved to an app-button temporarily because of styling challenges that I had.
This PR moves us back to using that component on the home page
=> chore(): use loading button on the home page

src/script/pages/app-home.ts
Bugfix
We were re-trying starting the tests in the `catch` block for when we were not able to retrieve a site (404 / 422 type situations) which led to incorrect error handling behavior.
We now go straight to the error state in this block instead of re-trying.
=> fix(): dont re-try in the could not get site error block

workbox.mjs
Bugfix
We shouldnt try to cache json as it catches `routes.json` which is only used by azure static web apps and causes a 404 when the sw tries to cache it. Because of this, the sw fails to install.
Not trying to pre-cache json.
=> fix(): dont try to cache json

src/script/pages/app-index.ts
Fixes #
https://github.com/pwa-builder/PWABuilder/projects/3#card-60816382
Bugfix
We had moved back to an async import for the report-page so we did not have to import the report-page component in the index. However, because we are (and we need to) programmatically navigating to the report-page we need to import it directly so things are already in memory. At the core, I "think" this might be a vague bug in the vaadin router, but I cant say that for sure.
We are now importing it directly again.
- [x ] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/de …
=> fix(): import report-page directly again

src/script/components/loading-button.ts, styles/global.css
- Bugfix
Set variable for the standard button height as a variable.
=> loading-button set variable for button height

src/script/pages/app-home.ts
Fixes #
Other... Please describe: CSS Fix
Paragraphs on the home page were too wide and almost running into each other.
These paragraphs now match the design.
=> fix(): intro grid item paragraphs should have standard width

src/locales/en_US.json, src/script/pages/app-home.ts, src/script/utils/url.ts
Fixes #
Bugfix
URLs are handled correctly without making that first test request to tell if its a valid URL or not. This code has also been simplified alot. My next step is to write a backend function that grabs the canonical URL and send that back to the front-end. I will then update the URL that is used for publishing with that canonical URL. This will handle the pinterest + android packging situation.
=> feat(): simplify URL handling

src/script/services/app-info.ts, src/script/services/manifest.ts
Fixes #
Bugfix
This fixes a bug where even if the non-canonical URL is being used for testing (such as https://pinterest.com) we will update the URL being used for packaging with the canonical URL (from our backend manifest finder services) in the background. This adds no new latency for the user to init the tests, but also ensures that once it comes to packaging the correct URL is being used (this is especially important for Android).
Once we have the canonical URL from our manifest finder services I call a function to update the URL being worked on with this more correct URL. This all happens without any need for action from the user. …
=> feat(): update url being used for packaging with canonical URL in the background

src/script/components/manifest-options.ts, src/script/services/manifest.ts, src/script/services/publish/index.ts, src/script/services/publish/web-publish.ts
Fixes #
https://github.com/pwa-builder/PWABuilder/projects/3#card-61981537
Bugfix
This PR fixes the following bugs:
- The manifest editor can now see a generated manifest
- The manifest editor can now successfully edit both a generated manifest and one from an app, and update the state correctly too.
- The above fix also fixed a bug with not being able to download on the base_package page
- A manifest is only generated once now if needed, the previous code could potentially generate it multiple times, wasting network time, azure cost etc etc
- [x ] Ensure that your contribution follows [standard accessibility …
=> fix(): manifest generation, editing and downloading fixed

src/script/components/android-form.ts, src/script/services/publish/android-publish.ts, src/script/services/publish/index.ts, src/script/services/publish/publish-checks.ts
Fixes #
Bugfix
We were checking strictly for a 512x512 icon for our final checks. This is an inaccurate check as a 512x512 is not "needed" for Windows package generation.
On Android, we had some methods that needed to be awaited, like the issue I fixed with package generation for Windows yesterday.
Icon issue: Changed our icon check to use our findSuitableIcons method to standardize our icon checks. 
Android: Awaited some methods that are now async.
- [x ] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design). Use tools like https://webhint.io/ to …
=> fix(): better icon check for finalChecks + android generation fix

src/script/pages/app-index.ts
Fixes #
Bugfix
When navigating between pages the scroll position was retained. This is because, like most PWAs, we are a single page app. However, Vaadin router makes it easy to customize the behavior on route changes.
We now listen for route changes and smoothly / performantly scroll to the top between navigations.
=> fix(): scroll to top on navigations

src/locales/en_US.json, src/script/pages/app-basepack.ts
Fixes #
Task 33586492
Bugfix
Text was wrong for the modal on the base_package page.
New, correct text for the download modal on the base package page
=> fix(): base package modal text is correct

src/script/pages/app-basepack.ts
Fixes #
Bugfix
Base package modal could get stuck closed when you hit the close button.
The modal works as expected now. I also changed the download to generate in the main page to match the publish page.
=> fix(): modal does not get stuck closed

src/script/pages/app-publish.ts
Fixes #
Bugfix 
Modals could get stuck closed when cancelled because of a state mismatch problem.
Modals no longer get stuck closed as we now update state correctly.
=> fix(): publish modals no longer get stuck closed

src/script/components/app-badges.ts
Fixes #
Bugfix
When hovering over the badges the label simply said "badges" instead of the actual name of the badge.
The name of the specific badge being hovered over now shows.
=> fix(): badge hover labels are correct

src/locales/en_US.json, src/script/pages/app-basepack.ts
Fixes #
Bugfix 
As David rightly points out in ADO, the next button on the base package page did not make sense as the user still does not have a manifest uploaded to their app at that point and therefore should not be able to easily go to the congrats page.
This PR removes the next button and keeps the Run New Test button, which is the more correct flow for users without a manifest.
=> fix(): remove next button from base_package page

src/script/components/windows-form.ts
Fixes #
Bugfix
Removes the start_url input from the Windows form as requested in a bug in ADO.
The start_url input is now not in the Windows form.
=> chore(): remove start_url input from windows form

src/script/components/tooltip.ts
Fixes #
Bugfix
Tooltips were getting cut off because they were on a "lower" layer than the surrounding modal.
Tooltips are now "position: absolute" to show above the modal layer with a tiny bit of JavaScript to ensure that they tooltips are positioned correctly (with the position being set to absolute we then need to handle positioning the element ourselves).
=> fix(): tooltips do not get cut off

src/script/services/publish/windows-publish.ts
Fixes #
Bugfix
The windows package classic version was only using the default value, not the value the user put in the form.
We now use the form value.x
=> fix(): make sure classic version input is passed when generating

src/script/components/manifest-options.ts
Bugfix
The color picker being used for the background color was just a standard HTML input. Also, I noticed that we had the background color input but not the theme color input.
We now use `input type="color"` so that we get the nice Chromium color pickers.  Also added the theme_color input and finally fixed a bug with the actual updating of the colors in the manifest.
=> fix(): use color picker and add theme_color picker

src/script/components/app-modal.ts, src/script/utils/dom-utils.ts
Fixes #
Bugfix 
When a modal was open, if you scrolled (such as you may need to do with the Windows or Android modals on the publish page, you could scroll the page underneath the modal.
This PR does what I've done with modals before, which is to set `overflowY` to hidden on the rootElement of the page (which will always be the html element in a normal browser context) to turn off scrolling and then set it back to initial once the modal is closed to turn on normal scrolling again.
- [x ] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design). Use …
=> fix(): cannot scroll the page when a modal is open

src/locales/index.ts, src/script/components/dropdown-menu.ts, src/script/components/manifest-options.ts
Fixes #
Other... Please describe: UX Update
Previously, the language input had a few design / ux problems. For one, the dropdown had no max-height, so for the language input it ended up being very large and going off the screen. Secondly, the dropdown only showed the language codes, not something that was easily "human readable".
The language dropdown now shows the actual names of the languages but still updates the manifest with the correct value (the language code). The dropdown also now has a max-height + some overflow CSS, preventing it from rendering off screen. I also tested the other dropdowns in this component to be sure I didnt break existing behavior, and I didnt.
- [x ] Target master branch (or an appropriate …
=> fix(): lang input UX updates

src/script/components/manifest-options.ts
Fixes #
Bugfix
The upload button was shown even before the file was chosen by the user (it was shown as disabled).
We now do not render the upload button until the file is actually chosen.
=> fix(): dont show upload button until file is ready

src/script/services/publish/web-publish.ts
Fixes #
Bugfix 
I updated the API call to match the updated API that Leo did for the web packaging service. I now pass the id of the chosen Service Worker along in the API call and also make use of the hasServiceWorker param correctly.
=> fix(): pass service worker id when generating base package

index.html, src/script/components/android-form.ts, src/script/components/code-editor.ts, src/script/components/manifest-options.ts, src/script/components/sw-picker.ts, src/script/components/windows-form.ts, src/script/pages/app-basepack.ts, src/script/pages/app-congrats.ts, src/script/pages/app-home.ts, src/script/pages/app-index.ts, src/script/pages/app-publish.ts, src/script/pages/app-report.ts, src/script/pages/app-testing.ts, src/script/utils/analytics.ts
Fixes #
Feature
No analytics were added to v3 yet, we only had our backend analytics.
V3 now has analytics for:
- All page navigations
- All page actions, from starting a test through to creating a package. Also tracks if the user is testing a non-pwa or a PWA.
Key details:
- Setup just like it was in v2, so all the data should be the same
- If you look in the code, it looks like im only sending 3 things, thats because the library sends a bunch of other data (it calls it "coreData") by default. I want to stress here that this is exactly how it works in V2 too.
- The Adobe analytics library gets blocked by the strict privacy mode in Edge, most likely gets blocked in Safari and im assuming in Chrome in certain configurations. This has also always happened with PWABuilder V2 and is not due …
=> feat(): add analytics to all page actions + all page navs

src/script/components/app-card.ts, src/script/pages/app-congrats.ts
Fixes #
The blog cards had links passed down in properties but were not using them as a link. Therefore, the idea in the design of the whole card being a clickable link was not working.
Each blog card is now a clickable link to the post, with the anchor tag styling reset with a small touch of css.
=> fix(): blog cards are now link tags

src/script/components/resource-hub.ts
Fixes #
View More Resources button was a button, not a link.
The View More Resources button, still looking like the design specifies, is now a link to the blog aka.ms url David set up.
=> refactor(): view more resources button is a link

src/script/components/app-card.ts, src/script/components/resource-hub.ts
Fixes #
Bugfix 
The cards in the resource hub on the homepage were not working.
These cards now work correctly with the right link.
=> fix(): blog links work on cards

src/locales/en_US.json, src/script/components/windows-form.ts
Fixes #
Other... Please describe:  text update
Removes the preview text from the Windows platform.
=> chore(): remove preview from Windows platform

src/script/components/android-form.ts
Fixes #
Bugfix
The proper placeholder text + default values have been added to match behavior from v2. Also temporarily backing out the local strings update as that is breaking my editor locally with a ton of TypeScript errors.
=> fix(): proper placeholders and default values

src/script/services/icon_generator.ts, src/script/services/screenshots.ts
- Bugfix
- if the user has a manifest but doesn't have the entries for icons or screenshots, there's an exception thrown.
- default to an empty array and add it to the manifest
=> V3 - if screenshots array is undefined, use a new array

src/script/components/android-form.ts, src/script/pages/app-publish.ts, src/script/services/publish/android-publish.ts, src/script/services/publish/index.ts
Fixes #
Bugfix
If someone was signing a package with their existing signing key the file was not being passed in correctly to the generation process.
The signing key file is now passed into the generation process correctly
=> fix(): self signing key is passed in correctly

package.json, src/script/pages/app-home.ts
Fixes #1838, where Safari crashes during a Lit render cycle. This is a hacky workaround for now.
=> Fix for Lit crash

src/script/services/app-info.ts, src/script/services/manifest.ts
Fixes #1859 
Bugfix
This fixes a regression in V3. With V2, we were using the URL as the user entered it, but in V3 we had code that would set the URL being tested / used to the `new URL(host)` (basically) which is not the URL the user intended to use.
We no longer overwrite the URL with `new URL(host)` in our code, instead using the URL as the user entered. I have tested this with multiple apps, including the one in the attached bug.
- [x ] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design). Use tools like https://webhint.io/ to validate your …
=> fix(): do not overwrite user entered URL with the hostname

src/script/components/app-modal.ts
Fixes #
Bugfix 
Text was overflowing the side of the error modal if it was a longer block of text.
Text no longer overflows but instead just scrolls 
=> fix(): error modals no long overflow text over the side

src/script/services/publish/web-publish.ts, src/script/utils/environment.ts
#1864 
- Bugfix
If the json payload was too large (24mb), the service rejects the call. Rather than just upping the value until we get successful requests, using a form should provide more reliable calls.
Adds a form based post request, logic set so that apps with more than 10 declared icons uses this endpoint. The service in question parses the form and converts it into json before handling it, so the end product is the same.
=> add methods to handle the different body types and creating of the url

src/script/components/app-modal.ts, src/script/utils/events/modal.ts
Fixes #
Bugfix
If you opened one of the publish modals, then closed it and then tried to reopen it again the modal would not actually open.
The modalId param is now passed into the close event correctly, enabling the modals to now be opened and closed multiple times as expected.
=> fix(): modalId is passed in correctly

src/script/components/app-header.ts, src/script/components/manifest-options.ts, src/script/pages/app-basepack.ts
Fixes #
Bugfix
- The view code button for the manifest editor is now the same as it is in the design.
- The mobile menu button in the header that is currently un-used is now temporarily hidden
- Fixes a small grammar error
=> Misc design fixes

src/script/services/publish/web-publish.ts
was adding malformed json strings of arrays to the payload with logic error
Fixes #
#1892 #1897
- Bugfix
Error was caused by form data payload including toString() representations of arrays of objects after parsing the objects and adding them individually. Essentially it was assuming the data was strings. This malformed data doesn't pass the schema requirements on fastifies form data reader and thus throws the error.
formdata payload:
```
screenshots: { "src": "/example1.png", "type": "...", ...}
screenshots: { "src": "/example2.png", "type": "...", ...}
screenshots: [object Object],[object Object],...
```
Logic correction to prevent behavior. Omits the third entry in the payload above.
=> form data payload error

src/script/components/android-form.ts, src/script/pages/app-publish.ts, src/script/services/publish/android-publish.ts
Fixes #1841 by adding manifest URL to Android options. Needed to work around HTTP/2 and HTTP/3 sites.
=> Added manifest URL to Android options

src/script/components/windows-form.ts
Fixes #1907
Bugfix
I was under the impression that the max length of the package id was <50 but its actually <=50 characters long.
The input now has a maxlength of 50.
=> fix(): package id can be exactly 50 characters

src/script/components/android-form.ts
- Bugfix
The label name should be "Notification delegation" instead of "Fullscreen".
=> Fix wrong label

src/script/components/android-form.ts
Fixes #1910 and #1911 
Bugfix 
- Underscores were not allowed in the packageID input, which does not match the Android spec.
- A developer could put in a password that is too short
- Underscores are now allowed by the "pattern" attribute in the packageID input
- The password fields have a minlength set to 6
I also changed the name of the package ID input to Package ID instead of Package Name
=> Android form improvements

src/script/components/hover-tooltip.ts, src/script/components/manifest-options.ts, src/script/pages/app-publish.ts
Fixes #
Bugfix 
Reported in ADO: Current tooltips would show up in the wrong places on the manifest-options page, especially once scrolled. 
I have implemented a new component called `hover-tooltip`. This component is a tooltip that will always be positioned correctly, even with scrolling as its positioned just using CSS.
*Note* This new tooltip is now used everywhere but the publish modals as the "old" tooltips are working well there and I didn't want to risk breaking those in some way as part of this PR. I will make this change in a separate PR.
- [ x] Ensure that your contribution follows [standard accessibility …
=> Tooltips are aligned correctly

src/script/components/manifest-options.ts, src/script/services/icon_generator.ts
Fixes #
Bugfix
When uploading an icon we had four issues:
1. For sites that did not already have a manifest and we could not generate one for because of multiple issues (https://partyfavorz.com/) generating icons would fail.
2. Icons were not refreshing after generation succeeded, making it look like the service was not working.
3. Uploading a new icon to a PWA that already has icons would just add on to the existing icons in the manifest, instead of replacing the old icon.
4. The upload modal would not close automatically after generation finished.
This PR fixes the above issues:
1. Any site should now be able to generate icons.
2. Icons are now contained in a state variable so that we trigger lit's render pipeline https://lit.dev/docs/components/properties/, this ensures the icons are …
=> Image rendering fix

src/script/components/app-button.ts
Styles when hovering over the homepage links on Safari
When hovering over the card links on Safari, the background color is the default dark purple of Fast Elements. 
The background color is now set to transparent (same design as in other browsers). 
This is my first PR so yay :)
=> Fix Safari link styles

src/script/components/app-header.ts
Fixes issue reported in #1930 
Bugfix
When clicking on the site's logo on the header, the click is handled by a `goBack()` function that when not in the report card page, it calls `window.history.back()`. Because of this, users get redirected to Google (or whatever page they were on before) when on the homepage.
Now the function checks that the pathname is not `/` (i.e., the homepage) before going back in history.
=> Fix go back when clicking on header logo

src/script/services/manifest.ts, src/script/utils/interfaces.ts
Helps to address manifest issue for #1908 by better handling the scenario where a manifest is found but contains invalid JSON. This PR just updates the return type but doesn't add any UI/UX, as we're waiting on designer for that.
Feature
=> Updated manifest finder result type to better handle scenario where manifest exists but has errors

src/script/components/manifest-options.ts
Fixes #1942 
- Bugfix
- Remove invalid value for windows and android generation.
- Transparent is not an option given in the form, still settable in the manifest editor, but unlikely.
=> rm transparent from selectable options

src/script/components/manifest-options.ts
Fixes #
Bugfix
Currently, the generate button for the screenshots was disabled until the "change" event of the URL input was fired. The change event (just the built in onchange event for html inputs) does not fire until the user has hit enter or has tapped outside of the input, and therefore the generate button was not enabled until the user had done one of those actions.
We now enable the generate button on the `input` event. This does mean that a user could potentially try to generate screenshots on an unfinished URL, but that would require the user to intentionally do that, and you wouldn't say that Twitter is broken cause you cant log in just because you hit login before you finished your password.
- [x ] Target master …
=> fix(): generate button enabled in input event

src/script/components/manifest-options.ts
Fixes #
Bugfix
As opened on ADO, we had an issue where the screenshots and icons were trying to be shown before they were being generated.
The app-gallery (the component we use on mobile to show the icons and screenshots) is now hidden until those assets actually exist.
=> fix(): screenshots and icons are hidden until they exist on mobile

src/script/services/manifest.ts, src/script/services/tests/security.ts, src/script/services/tests/service-worker.ts, src/script/utils/environment.ts
Fixes #
-  We were still calling the old API to generate a manifest, since we want to shut down the old API this change was needed. 
-  Also, the call to the old API to generate the manifest was slow, and was a big part of why sites like msn.com are slow.
Bugfix 
We were still calling the old API to generate a manifest, since we want to shut down the old API this change was needed. 
Changes:
- We now call the new function I deployed this morning which generates manifests using the pwabuilder-lib (just like the old API). 
- The old API url is not even in the codebase anymore since this was the last usage of it.
This fixes two issues:
- Sites like MSN are horribly slow to test (the video below shows the new speed)
- This was our last connection to the old API …
=> New generate manifest function is used

src/script/components/code-editor.ts, src/script/components/manifest-options.ts, src/script/pages/app-congrats.ts, src/script/utils/events.ts
- Feature
Errors in the console because the debounce is being overloaded.
No error, performance improvement by using the observer to trigger paints during the resize event rather than the usual after paint.
=> resize observer implementation

src/script/components/manifest-options.ts, src/script/services/publish/web-publish.ts
- Bugfix 
The preview component's reference to the manifest object is stale when inputs are changes. Refreshing the stale reference is needed.
Refreshes the stale reference
=> Llee updates

src/script/components/android-form.ts, src/script/components/manifest-options.ts, src/script/components/windows-form.ts, styles/global.css
The style of placeholders in input text fields is quite similar to the input text, making them hard to distinguish. 
The placeholder text now has a lighter shade of grey (but not too light since it should still be readable). To further remark the difference between placeholders and the input text without sacrificing accessibility, the placeholders are also italicized. For example, here are the first 2 fields from the manifest options form:
=> Add placeholder styles

src/script/components/manifest-options.ts, src/script/utils/icons.ts
Fixes #
Bugfix
(This is related to the Alibaba issue). There are edge cases, so far only identified with one site, where we have an icon URL but that URL may not actually load.
I added a new function to the icon utils that does a quick check to see if the URL actually loads before displaying the icon. Before we displayed a broken image instead. This also makes it more clear to the user that they would need to upload an icon still.
- [x ] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design). Use tools like https://webhint.io/ to validate your …
=> fix(): check if icon actually loads before we try to display it

src/script/components/app-file-input.ts, src/script/components/app-modal.ts
Background hover color of modal button
Bugfix
The button on the "Upload icons" dialog has a dark background color when hovering, making the text unreadable. 
The background color remains transparent.
=> Change button hover color for Firefox

src/script/components/manifest-options.ts, src/script/services/manifest.ts
- Bugfix
- Feature
There was not way to delete the icons and screenshots, had the code to, but wanted a design just to double check.
Adding the staple ion-icon trash symbol button.
Also removed deepmerge usage, which has indeed improved object merging performance and stability.
=> Adding image delete to manifest, for both screenshots and icons 

src/script/components/dropdown-menu.ts
Removes extra scrollbars in the dropdown menu of the manifest options form, as well as the hover background color of those same fields (issue was visible in Firefox).
Bugfix
The dropdown menus of the manifest options form (eg the one for selecting the language) have needless scrollbars for each menu item. Also, when hovering over these fields on Firefox, the background color darkens.
No extra scrollbars and no background color change.
=> Delete extra scrollbars

.github/PULL_REQUEST_TEMPLATE.md, src/script/components/app-gallery.ts
In the app-gallery file, lit elements are currently being imported from `lit-element` instead of `lit`, and the deprecated `internalProperty` decorator is being used. This is the only file that uses `lit-element`.
Import elements from `lit` and replaced `internalProperty` by `state`, as suggested by the docs.
=> Replace lit-element import by lit

src/script/services/manifest.ts, src/script/utils/interfaces.ts
When analyzing several websites consecutively, scores are not properly updated.
Bugfix
When analyzing different websites one after the other, the manifest and the score aren't properly updated. To reproduce:
- Enter "pwabuilder.com"
- Once in the report card page, click the "go back" browser button until you reach the home page again.
- Enter "bbc.com"
- The report card page is still using PWABuilder's manifest and score. If you only try "bbc.com" in a new tab, you will see that their score is 30.
The score is properly updated when the site changes. Sometimes (I haven't been able to recognize exactly when) the manifest options form still reflects an old manifest, so this should continue being investigated.
=> Fix score refresh

src/script/pages/app-index.ts, src/script/utils/url.ts
Bugfix 
When refreshing the page from the report card page, the page goes blank with an error message of "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."
The report card is now also lazy-loaded by the router.
=> Lazy load report page

src/script/services/app-info.ts, src/script/services/manifest.ts, src/script/utils/interfaces.ts
Bugfix
If you already had a manifest, but then used the manifest editor to edit it, you would not be sent to the base package page, therefore you could not download your edited manifest.
PWAs that edit their manifest will now be sent to the base_package flow.
=> bug(): edited manifests send to base package

src/script/components/app-header.ts, src/script/pages/app-home.ts
https://dev.azure.com/microsoft/OS/_workitems/edit/35285856/
Bugfix 
- Header logo could not be tabbed to by default
- Enter URL should not have autofocus so it does not steal focus
- Header logo should be able to be acted on by the keyboard
- Header logo is now tabIndex=0 as it is the top left element on the document.
- Removed autofocus from Enter URL input.
- Header logo now handles the keydown event so that it can be acted on with the keyboard in the expected manner.
- [x ] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design). Use tools like …
=> fix(accessibility): logo can now be tabbed to and acted on with keyboard

src/script/components/app-header.ts, src/script/components/content-header.ts, src/script/pages/app-congrats.ts, src/script/pages/app-home.ts, src/script/pages/app-publish.ts, src/script/pages/app-report.ts
Fixing h1, h2, h3, h4 hierarchy for screen readers
Bugfix 
missing h1 on all our pages, moving the tree to 1 level up
Screen readers can now see H1s on each page
=> Accessibility bug 35223716

src/script/services/app-info.ts, src/script/services/tests/manifest.ts
Bugfix 
If you came into PWABuilder with a manifest already, we were assuming it had icons etc and therefore they would be taken to the publish page. However, this assumption has been proven to be wrong.
When deciding to send the user to the publish or base_package route we now double check that their custom manifest has the following: 
- 512 icon
- start_url
- name
- short name
=> fix(): check icons, start_url, short_name and name

src/script/services/manifest.ts, src/script/utils/interfaces.ts
Refactoring
Warnings and errors from manifest detection service are ignored.
Warnings and errors from manifest detection service are returned in the response. No UI right now to show them, though we should do this when implementing #1575
=> Propagating manifest warnings to front-end

src/script/pages/app-home.ts
Other... Please describe: UI improvement
We use a custom font as specified by our design. While this font loads, we display the default sans-serif font. Unfortunately, this font has some slight width differences from our custom font which caused the header width to change when the custom font loaded in, causing the page to "jump" on certain sized devices.
The max-width of the header on the home page is tweaked slightly so that the header width stays constant when the custom font has loaded in (which can take a second on slow networks)
- [x ] Ensure that your contribution follows [standard accessibility …
=> fix(): header width now matches when the font loads

src/script/services/tests/manifest.ts
Bugfix
While we checked for the correct size for the main app icon (512x512 or larger), if that icon were found we never actually checked if it could be successfully loaded. This leads to a situation where a user can make it to the publish page with a busted icon link.
For the main app icon, the 512x512 or larger icon, we now have an additional test (that is reflected in the report-card page in the manifest section) that checks to see if the 512x512 or larger icon can successfully load. The next step in this path will be surfacing this check in our "errors UI" if it does error out, along with some other key problems identified here https://github.com/pwa-builder/PWABuilder/issues/1575.
- [x ] Target master branch (or an …
=> feat(): check if icons load successfully

src/script/components/app-modal.ts, src/script/pages/app-home.ts
https://dev.azure.com/microsoft/OS/_workitems/edit/35345688/
Bugfix
Error prompt on homepage was not being focused as it should and also did not have the right aria attributes.
Both the error prompt setup on the home page and our modals (which includes the error modal) now have the correct aria attributes. I also focus the error prompt manually for the user when there is an actual error.
=> Start errors a11y

src/script/pages/app-testing.ts, src/script/services/tests/index.ts
Bugfix
Feature
There was recently a discussion with @JudahGabriel about the potential for people to get stuck on the testing page in certain error situations. While this hang is alot harder to reproduce nowadays, we still have one case where a user is wanting to use an IP address as their URL (which points to our need for local tooling) that will cause an error. To ensure that no one ever gets stuck on the testing page without some kind of user feedback, I have implemented new behavior.
We now use our error modal on the testing page.  This ended up requiring two changes:
1. Using the scenario described above I discovered we had one key place where we were not catching errors, the runAllTests function. I improved the error handling of this function to makes sure that the promise rejects. …
=> fix(): improve error handling + new error modal for testing page

src/script/components/android-form.ts
Fixes an issue where Android App Name wrongly disallowed a space in the name.
Bugfix
Android app name can't contain a space. Android form control says the value is invalid.
Android app name allows a space.
=> Allow space in Android app name

src/script/components/android-form.ts, src/script/components/app-package-form-base.ts, src/script/components/hover-tooltip.ts, src/script/components/info-circle-tooltip.ts, src/script/components/ios-form.ts, src/script/components/manifest-options.ts, src/script/components/windows-form.ts, src/script/pages/app-congrats.ts, src/script/pages/app-publish.ts, src/script/pages/portals-publish.ts, src/script/services/publish/android-publish.ts, src/script/services/publish/index.ts, src/script/utils/analytics.ts, src/script/utils/android-validation.ts, src/script/utils/environment.ts, styles/form-styles.css
Fixes #2219, fixes #2211, fixes #2249
Bugfix
- The Android form wasn't always setting the manifest URL properly. 
- The Android form had a great deal of duplicate code.
- The hover tooltip didn't work well on scrollable modals.
- The Android form sets the manifest URL correctly.
- The Android form has been refactored to be more DRY, reduced by about 400 lines of code.
- The hover tooltip has been reworked to use absolute position. I tested and verified it works correctly on the manifest options page, on the packaging modals, and on the publish page. 
- Adds an additional component, `<info-circle-tooltip>`, that draws a ❓ circle + hover to get a `hover-tooltip`.
=> Fixed Android form. Better tooltip component.

rollup.config.dev.js, tsconfig.dev.json, web-dev-server.config.mjs
The problem where the page would reload 3x when a watched file changed.
When running npm dev and you made a single change to a TS file, the app would reload 3x in browser.
The app reloads just once after a change has been made.
=> Faster builds, faster loads from watch file change

src/script/components/sw-picker.ts
ref #2228
#2228
Bugfix 
This is an attempt to fix the content in the service worker options, which is breaking the layout as related in the issue, this is the current behavior:
This is how the page looks with this change:
=> fix: attempt to make the content fit in the container

package-lock.json, package.json
Bugfix
The browser-fs-access library automatically handles fallbacks for platforms that do not support the fileSystem api, however we were on an older version of the library, much older.
Updated to the latest version of the library
=> chore(): update browser-fs-access for better fallback

src/script/components/android-form.ts, src/script/components/app-modal.ts, src/script/pages/app-publish.ts
https://github.com/pwa-builder/PWABuilder/issues/2302
Feature
Other stores are forced to use the signed apk option we have by default
New nav bar in android options modal (on click of generate package). Allows for unsigned apk's to be generated.
=> Other Stores UI

src/script/components/oculus-form.ts, src/script/services/publish/oculus-publish.ts, src/script/utils/oculus-validation.ts
Adds `VersionName` and `Url` to Oculus package args.
Current version omits VersionName and `Url`.
New version includes VersionName and gives UI for it. Adds `Url` being analyzed by PWABuilder.
=> Added version name and additional signing key info

src/script/services/publish/android-publish.ts, src/script/utils/android-validation.ts
Adds more URL precision to Android platform backend analytics.
Feature
We send to Android platform the host URL for analytics purposes.
We send in the URL given by the user to PWABuilder.
=> Adds pwaUrl to Android platform

src/script/components/app-sidebar.ts, src/script/components/rating-dial.ts
https://github.com/pwa-builder/PWABuilder/issues/2483
Bugfix
The rating dial in the side bar was not correctly displaying the score of the PWA. This was due to a network call that was failing.
Eliminated the network call and now we handle the averageScore on client side.
=> Rating Dial Complete fix

src/script/components/windows-form.ts, src/script/utils/win-validation.ts
#2590 #2591 
Bugfix
Feature
Checkbox to opt out of publishing package that would target Windows.Holographic
=> Added ability to opt out of targeting hololens while packaging for windows

src/script/pages/app-report.ts, src/script/services/app-info.ts
#2580 
Bugfix 
When using the link to the report card is displays the incorrect total score.
Report card now displays correct total score when opening the report card in a new tab. If someone needed to share their report card link for a group project, etc, the link will display the correct info.
=> Link to report card displays correct total score

src/script/components/cookie-banner.ts, src/script/utils/analytics.ts
https://github.com/pwa-builder/PWABuilder/issues/2516
Feature
Banner does not give the option to reject non-essential cookies.
Banner now gives the option to reject non-essential cookies. If the ignore the banner, it works the same as rejecting.
@joshsach, this will probably cause a drop of in our analytics since the only essential analytic cookie is tracking page views.
=> New cookies banner that allows users to accept/reject

src/script/components/android-form.ts
#2666 
Bugfix 
Input fields had the same ID leading to duplicate aria-id flag
Specific id added
=> Duplicate input id fix

src/script/utils/manifest-validation.ts
#2650
Bugfix 
User has categories in their manifest, but it is not in the standard list here https://github.com/pwa-builder/PWABuilder/blob/e5764f13d21846a5c97d3239c337be3eb81db494/src/script/utils/manifest-validation.ts . The user is told in the report-card page that they don't have categories even though they do, they are just non-standard.
Specifies if the category is non standard
=> Category in report card specifies if it is non standard or non existent

.github/ISSUE_TEMPLATE/feature_request.yaml, src/script/components/app-footer.ts, src/script/components/app-header.ts, src/script/components/rating-dial.ts
We discussed the importance of being consistent with how we spell and space PWABuilder. It seems like PWABuilder (with no space) seems to be used more widely so we decided to move forwards with that one.
=> "PWA Builder" to "PWABuilder"

src/script/services/app-info.ts, src/script/services/manifest.ts
https://github.com/pwa-builder/PWABuilder/issues/2834
Bugfix
Theme and Background colors set to `none` in our empty manifest which causes errors down the line for users
Theme and Background colors set to `#000000`
=> theme and bg color in manifest set to #000000 rather than none

src/script/pages/app-home.ts, src/script/utils/analytics.ts
https://github.com/pwa-builder/PWABuilder/issues/2837
Bugfix
Demo url gets tracked as a normal process and theres no way to know if this test url is inflating our numbers.
Demo url gets its own process so it won't impact the normal flow numbers.
=> added demo url flag to separate out the process where demo urls are used

src/script/components/code-editor.ts, src/script/pages/app-home.ts, src/script/pages/app-report.ts
https://github.com/pwa-builder/PWABuilder/issues/2883
Bugfix
The direct link to the PWA Studio Marketplace page is in the site.
The aka.ms link replaces the direct link.
=> added aka link to home page

apps/pwabuilder/src/script/components/discord-box.ts
#2888 
Bugfix
apps/pwabuilder
The close button was not accessible by keyboard (tab).
Close button should now be focusable when tabbing through the page.
=> Keyboard focus added to close button on discord modal

apps/pwabuilder/src/script/pages/app-home.ts
#2906 
Feature
apps/pwabuilder 
User can navigate (through mouse or using Win + CTRL + Enter then tab key) to start button without any text in the input field
Text must be placed in the input field and validated before start button is accessible
=> Start button is disabled until input is true for isValidUrl()

apps/pwabuilder/src/script/components/success-stories.ts, apps/pwabuilder/src/script/pages/app-home.ts
fixes #2889 
Background image missing alt to signify decorative purpose
Empty alt added to signify decorative purpose
=> [PWABUILDER] Empty alt added to decorative css generated background imgs

apps/pwabuilder/src/script/components/info-card.ts
#2887
Decorative icons on the homepage cards were scanned when opening the screen reader and pressing the down key
Decorative icons on the homepage are no longer scanned
=> Nonfocusable decorative icons

apps/pwabuilder/src/script/pages/app-home.ts
[#2907](https://github.com/pwa-builder/PWABuilder/issues/2907)
‘Ship your PWA to apps store’ label is not associated with ‘Enter the URL to PWA’ edit field. Screen reader dependent user will not be able to figure out the meaning of the Edit field.
Ship your PWA to apps store label is associated with ‘Enter the URL to PWA’ edit field
=> URL Input field associated to header

apps/pwabuilder/src/script/components/success-stories.ts
[#2891](https://github.com/pwa-builder/PWABuilder/issues/2891)
User was not able to differentiate the different success stories through the screen reader
Short title (ex: "Trivago's success story") added to signify the start of a new story. Only readable with a screen reader, not visible.
=> Screen reader only success stories titles

docs/README.md, docs/studio/create-new.md, docs/studio/existing-app.md, docs/studio/faq.md, docs/studio/package.md, docs/studio/quick-start.md
Just reading through the PWA Studio docs looking for broken links and typos. I fixed a few with this PR but there are still a few broken links that I'll note below. I added @jgw96 to verify that I am making corrections that are consistent with what you intended to write and also @zateutsch so he can add the correct links.
Format is **location = problem**
quick start / First steps = full of broken github wiki links
create new / next steps = broken github wiki link
existing app / first paragraph =  "validate" has no link (idk where its supposed to go)
existing app / adding a manifest = does adding a manifest still work like this in 1.0?
existing app / generate icons = 512x512 link links to documentation @ blog.pwabuilder.com
existing app / generate icons = instruction 1 broken link to …
=> typos and links that I could fix

apps/pwabuilder/src/script/components/app-header.ts
fixes half of #2983 other half will be in the blog repo
Feature
Only like to blog via Resources link
New link to docs and blog with two new links
=> changes to nav to split the resources into two new links

docs/index.html
fixes #2878 
Analytics should track PageViews now. All docs Page names are prefixed with `docs`.
=> 2878 Add Analytics

apps/pwabuilder/src/script/components/app-footer.ts, apps/pwabuilder/src/script/pages/app-home.ts
[#2912](https://github.com/pwa-builder/PWABuilder/issues/2912)
Icon color does not change in high contrast mode. The narrator keyboard indicator is not visible on the input field in high contrast mode. Text in the input field is dark in high contrast mode.  
High contrast mode css is implemented for the icons, and input field.
=> High contrast css

apps/pwabuilder/src/script/components/companies-packaged.ts, apps/pwabuilder/src/script/pages/app-home.ts
[#2912](https://github.com/pwa-builder/PWABuilder/issues/2912)
Button color must change in all high-contrast-themes
Color is changed in high-contrast
=> Carousel button color must change in high-contrast mode

apps/pwabuilder/src/script/components/success-card.ts
fixes #2891 
Bugfix
Hit tab to a success card, after hit the down arrow key to focus on its contents. It should focus on the percentage at the top, but it does not.
The focus starts at the percentage value and from there can be navigated down (using down arrow key) to read the rest of the content.
=> scanner focuses on the percentage value first after tabbing onto card

docs/builder/quick-start.md
The `iOS` folder was renamed at some point to `app-store` but the next steps link was missed with the rename.
- Bugfix
- Documentation content changes 
User clicks on the `iOS App Store` link at `https://docs.pwabuilder.com/#/builder/quick-start` and gets a 404
User clicks on the `iOS App Store` link at `https://docs.pwabuilder.com/#/builder/quick-start` and gets routed to the correct content
=> Fix broken link to Apple App Store's next steps

docs/hidden/asset-links-faq.md
Very minor bug fix.
The sidebar for the assets links article was displaying incorrectly.
Added ignore labels to fix.
=> [DOCS] Fix asset links sidebar bug

apps/pwabuilder/src/script/pages/app-home.ts
- Bugfix
"Start a new PWA" link is broken and points to the old wiki that doesn't exist anymore
The link points to our new docs
=> Fixed link to starter docs

apps/pwabuilder-vscode/src/services/validation/sw-view.ts
fixes #3315 
Bugfix
Studio would not see that a service worker had been registered in the PWA Starter as we use the Vite "regsiterSW.js" script in the starter for prod builds. 
Added back a specific check for the starter. Note: Stuff like this could be used to help know if an app is a PWA Starter app or not.
=> fix(vscode): specific sw register check added back for starter

apps/pwabuilder-vscode/src/services/manifest/assets-service.ts
fixes #3318
Bugfix
While PNG is the recommended format for icons because of transparency support (https://developer.chrome.com/docs/extensions/mv2/manifest/icons/#:~:text=Icons%20should%20generally%20be%20in%20PNG%20format%2C%20because,JPEG.%20Here%27s%20an%20example%20of%20specifying%20the%20icons%3A), we should still allow users to choose other supported image types.
User can now choose other supported image types besides png
=> fix(vscode): can choose other image types besides png

apps/pwabuilder/src/script/components/android-form.ts
fixes #3344 
Bugfix
There was an upper limit on the number of chars that could be in the android package id. This is incorrect as there can be longer id's.
New upper limit set to Number. MAX_SAFE_INT to simulate no char limit.
=> Remove upper char limit on android package id

docs/home/resources.md
Mozilla was misspelled in this article (Mozzilla), so I changed it, but then realized that MDN is a far more well-known term to refer to the docs than Mozilla. So I changed it to MDN.
I also realized there was no mention of our own docs here, so I added a section.
=> Added DMC resources and changed Mozilla->MDN

components/manifest-editor/package-lock.json, components/manifest-editor/package.json, components/manifest-editor/src/components/manifest-icons-form.ts, components/manifest-editor/src/components/pwa-manifest-editor.ts, libraries/manifest-validation/src/index.ts, libraries/manifest-validation/tsconfig.json
Bugfix
Was having problems using the manifest-editor during the hackathon because of Webpack complaining about the CDN URLs and them using dynamic imports, which Webpack STILL has limited support for in 2022.
I now import the two shoelace components we are using from the shoelace NPM package.
=> fix(mani-editor): use shoelace from npm instead of CDN

apps/pwabuilder/src/script/pages/app-report.ts, components/manifest-editor/src/components/manifest-info-form.ts, components/manifest-editor/src/components/manifest-platform-form.ts, components/manifest-editor/src/components/manifest-settings-form.ts
fixes 
- #3557 
- #3548 
- #3563 3563
- Duplicating error messages in ME
- Added feature to open ME or SW picker if you click the below action items
Bugfixes
Feature
- If you don't have a manifest, we create one and then score the created manifest
- MDN dropped full support for the `lang` field and removed the URL so on our site it is a dead link
- populateAppCard choses the first icon in the list of icons for app-card which sometimes is the smallest icon so it appears blurry
- After you generate a screenshot, error messages on the info tab were showing twice
- When you click those action items it just opens the details.
Respective to the fixes list.
- Even if we create a manifest, we will score an empty one and still show them the created one in the ME. This will make sure that in the …
=> Bug fixes listed Below

apps/pwabuilder/src/script/components/manifest-editor-frame.ts, apps/pwabuilder/src/script/components/publish-pane.ts, apps/pwabuilder/src/script/components/sw-selector.ts
Bugfix
You can't X out any modal on the report card page on ios
I noticed it was technically a lower z-index than other things ahead of it which could contribute to why you couldn't click. This is more of an experiment just to see if it will work on ios. This change has no other visible or functional effect.
=> potential fix to close button issue on ios

.github/ISSUE_TEMPLATE/packaging_error.yaml, apps/pwabuilder/src/script/components/publish-pane.ts, apps/pwabuilder/src/script/components/test-publish-pane.ts
fixes #3562 
Feature
Bugfix
1. No template for packaging errors
2. There was an issue where some windows errors showed incorrectly in the error box
1. New template for packaging errors specifically
2. The way we parse windows errors now covers more formats for both regular and test packages
=> New Issues template + windows error message fix

apps/pwabuilder-vscode/package.json
fixes https://github.com/pwa-builder/PWABuilder/issues/3556
Bugfix
The extension would always try to activate after VSCode had finished loading, meaning it would use the CPU even if you had never used the extension.
We now only activate the relevant parts of the code when they are needed, instead of trying to activate the whole extension. This could also mean that it may take just a little longer to find the manifest and service worker, but respects the user MUCH better by only doing this once they start using the extension.
=> fix(): dont use onStartupFinished event

apps/pwabuilder/src/script/components/manifest-editor-frame.ts, apps/pwabuilder/src/script/components/publish-pane.ts, apps/pwabuilder/src/script/components/sw-selector.ts, apps/pwabuilder/src/script/pages/app-report.ts
- When the user didn't have a SW the last two cards would become misaligned for about 100px before the snapped into a column, that is now fixed.
- Added comments to `publish-pane`, `sw-selector` and `manifest-editor-frame` on new functions that didn't exist pre redesign. Just adding clarity on future devs to come.
=> Fixed CSS issue on report card page + more comments in code on new functions in the modals of the RC page.

apps/pwabuilder/src/script/components/app-header.ts
fixes n/a
Test
When you mouse over community it appears but its doesn't disappear until you click
If you mouseover the community label when its open, it will now close.
=> Mouseover behavior for Community dropdown in nav bar

apps/pwabuilder/src/script/components/community-card.ts, apps/pwabuilder/src/script/components/cookie-banner.ts, apps/pwabuilder/src/script/components/info-card.ts, apps/pwabuilder/src/script/pages/app-home.ts, apps/pwabuilder/src/script/pages/app-report.ts
fixes #3606
Bugfix
Some fonts were too small on mobile sizes and the cookies banner makes putting promotional stuff at the top banner area a big stacking mess.
Cookies banner floats at the bottom until interacted with
Font size increase where necessary on mobile sizes
=> Cookies banner fixed to bottom + Mobile size font increase

libraries/manifest-validation/src/validations.ts
fixes #3635
Bugfix
We were allowing people to see the package for store button if they had non-hex encoded color strings for background and theme colors.
If they choose to use those two fields, the test requires it to be hex or else they can't package.
=> fixed background and theme color issue

apps/pwabuilder/src/script/pages/app-report.ts
fixes #3647
Bugfix
Missing required fields are not blocking packaging.
Missing required fields block packaging.
=> Missing required fields were not properly blocking packaging

apps/pwabuilder/package.json, apps/pwabuilder/src/script/pages/image-generator.ts
fixes #3650
Bugfix
When we switched the page /imageGenerator to use shoelace instead of fast elements I didn't change the input events to be `@sl-change` rather than just `@change` therefore, no changes were being tracked.
Changed `@change` to be `@sl-change` so that change is properly tracked on the padding input, color radio group and packaging checkboxes.
=> Updated /imageGenerator to properly change when the inputs are changed

apps/pwabuilder/src/script/components/publish-pane.ts, apps/pwabuilder/src/script/components/test-publish-pane.ts
There was an issue with our error boxes that would cause them to overflow in some scenarios and this PR fixes that.
=> fixed overflow issue with error boxes

libraries/manifest-validation/src/validations.ts
fixes #3675
Bugfix
Categories validation check doesn't check if the value is an array which leads to packaging errors.
Categories validation check lets you know you failed if your field is not an array.
=> Categories was missing isArray check

libraries/manifest-validation/src/index.ts, libraries/manifest-validation/src/validations.ts, libraries/manifest-validation/test/validation-tests.js
fixes part of https://github.com/pwa-builder/PWABuilder/issues/3417
Bugfix
Shortcut icons were not validated for size
Shortcut icons are now validated to have atleast one 96x96 icon.
=> fix(validation): shortcuts are validated for minimum icon size

apps/pwabuilder-vscode/package-lock.json, apps/pwabuilder-vscode/package.json, apps/pwabuilder-vscode/src/extension.ts, apps/pwabuilder-vscode/src/library/package-utils.ts, apps/pwabuilder-vscode/src/services/dashboard/dev-dashboard.ts, apps/pwabuilder-vscode/src/services/manifest/assets-service.ts, apps/pwabuilder-vscode/src/services/manifest/manifest-service.ts, apps/pwabuilder-vscode/src/services/new-pwa-starter.ts, apps/pwabuilder-vscode/src/services/package/package-android-app.ts, apps/pwabuilder-vscode/src/services/package/package-app.ts, apps/pwabuilder-vscode/src/services/service-workers/adv-service-worker.ts, apps/pwabuilder-vscode/src/services/service-workers/service-worker.ts, apps/pwabuilder-vscode/src/services/service-workers/simple-service-worker.ts, apps/pwabuilder-vscode/src/services/usage-analytics.ts, apps/pwabuilder-vscode/src/services/validation/validation-view.ts, apps/pwabuilder-vscode/src/services/validation/validation.ts, apps/pwabuilder-vscode/src/services/web-publish.ts, apps/pwabuilder-vscode/src/test/runTest.ts, apps/pwabuilder-vscode/src/views/icon-view.ts
fixes #3718 
Feature
We are using the applicationinsights lib directly, which does not work well for a vscode environment (or really any local node experience).
We are now using the (currently in preview) vscode telemetry module. While it is in preview, the upsides of using this official module and how it solves issues with our analytics is worth the preview module.
=> feat(studio): use vscode telemetry module

apps/pwabuilder-vscode/package.json, apps/pwabuilder-vscode/src/services/usage-analytics.ts
fixes #3732
Bugfix
There is an underlying issue with the reporter library, however this fix gets past the issue that keeps people from being able to use the command.
Check if the reporter object is available before using. This object should always be there, but due to an issue with the reporter library, it is not.
=> fix(): if reporter is not available dont try to call

apps/pwabuilder/package-lock.json, docs/builder/manifest.md, libraries/manifest-validation/src/validations.ts
fixes #3757
Bugfix
Short name was required to be >= 2 chars. This would cause failures on the ios service.
Increased the requirement to >= 3 chars which makes it so you can't package. Also added a note in the docs.
=> Added new short name requirement of >= 3 chars

components/manifest-editor/src/components/manifest-settings-form.ts
Bugfix
In the manifest editor, despite clicking a checkbox, nothing would happen when trying to edit the display_override field
Now it works as expected.
=> [Manifest Editor] display_override fix

apps/pwabuilder/src/script/components/manifest-editor-frame.ts, apps/pwabuilder/src/script/components/windows-form.ts, apps/pwabuilder/src/script/services/publish/windows-publish.ts, apps/pwabuilder/src/script/utils/win-validation.ts
fixes https://github.com/pwa-builder/PWABuilder/issues/3816
Feature
No way to flag that you have widgets
way to flag that you have widgets. 
**Note: Checked by default if widgets are present in the manifest**
You may not be able to get there with the preview link but it looks like this at the bottom of the windows packaging form
Also, I snuck in adding a new analytic tag to count for when tabs are swapped in the manifest editor.
=> added widgets toggle

apps/pwabuilder/src/script/components/todo-list-item.ts, apps/pwabuilder/src/script/pages/app-report.ts
fixes #3586
Bugfix
When you switch pages, the action items pane resizes.
The pane is now a set height and the todo items are aswell, when you switch pages, everything stays. Only thing is that everything is a bit thicker, but the space feels good.
=> Action items pane doesn't resize on page change

apps/pwabuilder/src/script/components/app-package-form-base.ts, apps/pwabuilder/src/script/components/windows-form.ts
fixes #3873
Feature
If you didn't have widgets, you were still able to check the box in the windows form saying to serve widgets for your package which changes the way the .msix is built unnecessarily. 
You can only toggle the widgets checkbox if you already have widgets in your manifest. Otherwise, it'll be disabled.
=> Disabled widgets checkbox if manifest doesn't have widgets

apps/pwabuilder/src/script/components/android-form.ts, apps/pwabuilder/src/script/components/app-package-form-base.ts, apps/pwabuilder/src/script/components/windows-form.ts
fixes #3898
Feature
I originally created a new color picker option in the Windows packaging form for the Icon background color. I then realized that the android and ios forms also use color pickers and things were not uniform.
I created a generic color picker that can just be used by calling the same `renderFormInput` still with `type='color'` and the new color picker will be generated for all forms.
This is what it looks like:
=> Generic color picker added to `app-package-form-base` to be used across all forms

.github/workflows/pwabuilder-preview.yml, apps/pwabuilder/CONTRIBUTING.md
Dev is too far gone and we need a new clean staging link. If you have unfinished work on dev, it will still live on the dev branch, however, this branch will be live at preview.pwabuilder.com
=> new branch for preview.pwabuilder.com

docs/home/pwa-workshop.md
I updated the sample code in the [workshop](https://github.com/pwa-builder/pwa-journal-workshop) to reflect up-to-date pwa-starter template and make the UI look a bit more like a native app. This PR includes updated sections in the docs workshop page.
=> Update workshop content based on updated pwa-starter

apps/pwabuilder/src/script/components/publish-pane.ts, apps/pwabuilder/src/script/components/test-publish-pane.ts, docs/builder/faq.md, docs/builder/manifest.md, docs/builder/quick-start.md
fixes #4112 
Added new CSS for experimental to change color to red (welcome to push back to this). Also we can separate from the previously packaged look later on.
=> [SITE] Re-Enabled Experimental Tag for iOS

libraries/manifest-validation/src/mani-tests.ts
This shouldn't be causes people to FAIL the test. Edge doesn't raise an error. In the future we can raise this as a warning.
=> removed 96x96 requirement from shortcut validation

docs/assets/code-examples/example-sw.js, docs/home/pwa-workshop.md, docs/home/sw-intro.md
I found that in some cases, not using `self.` doesn't work. Updated docs to always include `self.`
=> [DOCS] making sw code more robust

apps/pwabuilder/src/script/components/app-package-form-base.ts
fixes #4267 #4301
Bugfix
When you change the color using the color picker in the android form, it breaks the signing mode sub form for some reason. Had to do with the way we were setting the color picker color label using `.innerHTML` or `.textContent`
We just completely replace the p element instead of changing the inner html.
=> [SITE] Fix color picker breaking signing mode sub form inside the android form

apps/pwabuilder/src/script/components/publish-pane.ts
fixes https://github.com/pwa-builder/PWABuilder/issues/4238
Bugfix
X button on portals pop up even tho you can't X it out 
Removed the X
=> [Accessibility] Removed close button from portals modal

apps/pwabuilder/src/script/pages/app-home.ts, apps/pwabuilder/src/script/pages/app-report.ts, apps/pwabuilder/src/script/pages/image-generator.ts, apps/pwabuilder/src/script/pages/qualification/app-token.style.ts, apps/pwabuilder/src/script/pages/qualification/app-token.ts, apps/pwabuilder/styles/global.css
fixes [#4229](https://github.com/pwa-builder/PWABuilder/issues/4229), [#4218](https://github.com/pwa-builder/PWABuilder/issues/4218) and [#4228](https://github.com/pwa-builder/PWABuilder/issues/4228)
Bugfix
1. For the padding input on the image gen page there was no accessible label
2. For some of our black buttons the focus ring wasn't showing when tabbed over
3. Incorrect aria roles defined
1. Input has a label
2. New visible focus ring.
3. Removed unnecessary definitions of role.
=> [Accessibility] Fixed focus no appearing on black buttons and label on input box in Image Gen page.

components/manifest-editor/src/components/manifest-icons-form.ts, components/manifest-editor/src/components/manifest-info-form.ts, components/manifest-editor/src/components/manifest-platform-form.ts, components/manifest-editor/src/components/manifest-screenshots-form.ts, components/manifest-editor/src/components/manifest-settings-form.ts, components/manifest-editor/src/components/manifest-share-form.ts
fixes [#4234](https://github.com/pwa-builder/PWABuilder/issues/4234)
Bugfix
If an error had appeared in the manifest editor, the screen reader wouldn't know
Added aria live = polite to the error messages so they are announced if they appear after updating an input
=> [Accessibility] Errors are announced as the appear in the manifest editor

docs/styles/global.css
=> color ratio fix

docs/builder/manifest.md
Update the example to what is specified in https://github.com/WICG/manifest-incubations/blob/gh-pages/scope_extensions-explainer.md
The example seems incorrect.
The example is changed to what is explained in the specification.
n/a
=> docs(manifest): correct web app origin association

apps/pwabuilder/src/script/components/todo-list-item.ts, apps/pwabuilder/src/script/pages/app-report.ts
fixes #4363
Bugfix
We had an if statement that blocked the validation tests from running on created manifests and since we populate the data using the results from those tests, it was empty
Unblock the tests and make sure they know its created and they need to update it
=> [Site] fall back for no manifest

apps/pwabuilder/src/script/components/publish-pane.ts, apps/pwabuilder/src/script/components/todo-list-item.ts, apps/pwabuilder/src/script/pages/app-report.ts
Removes the todo item and the banner on the Windows store card pushing users to the giveaway page.
=> [SITE] remove giveaway references from the report card page

apps/cli/README.md, apps/cli/package-lock.json, apps/cli/package.json, apps/cli/src/analytics/track-events.ts, apps/cli/src/analytics/usage-analytics.ts, apps/cli/src/commands/build.ts, apps/cli/src/commands/create.ts, apps/cli/src/commands/start.ts, apps/cli/src/util/util.ts
@jgw96 This contains the changes we talked about. I also added a readme for display on NPM.
If you could just update to **0.0.15** and make sure none of the commands hang that would be great.
Summary of changes:
The bulk of each command and the analytics process are now running on separate processes. I also detached the analytics process from the parent, and if I understand/tested correctly, we should get analytics regardless of whether or not the command was cancelled, unless they manage to cancel before we make the analytics call.
=> [CLI] Change Usage Tracking Behavior

docs/builder/app-store.md, docs/builder/manifest.md, docs/builder/meta.md, docs/builder/store-promotion.md, docs/builder/windows.md, docs/home/benefits-of-pwa.md, docs/home/native-features.md, docs/home/pwa-intro.md, docs/home/pwa-workshop.md, docs/home/resources.md, docs/home/sw-intro.md, docs/release-notes/2022.md, docs/starter/publish.md, docs/starter/quick-start.md, docs/starter/service-worker.md, docs/starter/tech-overview.md, docs/starter/ui-components.md, docs/studio/dev-dashboard.md, docs/studio/existing-app.md, docs/studio/quick-start.md
fixes #4258 
Bugfix
More descriptive "here" text across all docs
=> More descriptive "here" text across all docs

docs/studio/create-new.md, docs/studio/package.md, docs/studio/quick-start.md
fixes #4259 
Bugfix
Alt added to images throughout docs
=> Missing alt add for all docs

.github/workflows/pwabuilder-main.yml, .github/workflows/pwabuilder-preview.yml
fixes #4433 
Changelogs generated, along with a "release" tag here on Github, for both staging and prod builds. Changelogs are generated based on commits of course, staging builds are marked as a pre-release and prod builds are simply marked as a release. 
- [xx ] Target main branch (or an appropriate release branch if appropriate for a bug fix)
=> feat(): generate changelogs for staging and prod builds

docs/builder/asset-links-faq.md
=> [DOCS] #4426: clarify asset links location guidance

apps/blog/src/includes/sub-header.njk
- Bugfix
If a post has an updatedDate, it shows up twice
It only shows up once
=> [hotfix] [BLOG] Fixed duplicate date on blog posts

docs/builder/meta.md, docs/home/benefits-of-pwa.md, docs/home/pwa-intro.md, docs/home/sw-intro.md, docs/index.html, docs/starter/quick-start.md, docs/studio/dev-dashboard.md
=> [DOCS] #4526: Broken docs links

apps/pwabuilder/src/script/components/test-publish-pane.ts, apps/pwabuilder/src/script/components/windows-form.ts, apps/pwabuilder/src/script/services/publish/windows-publish.ts, components/manifest-editor/src/components/manifest-screenshots-form.ts
fixes https://github.com/pwa-builder/PWABuilder/issues/4401
Feature
Manifest background color is default for icon background
Transparent is default for icon background
This PR also disables the ability to generate screenshots as we feel generating base64 strings into peoples manifest is creating an inefficient system and people don't understand why its inefficient and trusting that PWABuilder is doing the right thing when it isn't. Part of the temporary solution described here https://github.com/pwa-builder/PWABuilder/issues/4550
=> Transparent new default for Windows Icon Backgrounds.

apps/pwabuilder/src/app-index.ts, apps/pwabuilder/src/script/pages/app-report.api.ts, apps/pwabuilder/src/script/services/publish/android-publish.ts, apps/pwabuilder/src/script/services/publish/ios-publish.ts, apps/pwabuilder/src/script/services/publish/oculus-publish.ts, apps/pwabuilder/src/script/services/publish/windows-publish.ts, apps/pwabuilder/src/script/utils/analytics.ts
fixes #4573 
Main Change:
On first visit to site, we now check for a `ref` query param and then store it in sessionStorage.
When making any calls to analytics or back end, check if we have stored a referrer value, and include it if we have.
Included changes:
- simplify page title setting logic
Marked as `DO-NOT-MERGE` as I still need to test some things and make sure back end PRs are merged first.
=> [SITE] #4573: Added campaign referrer tracking to PWABuilder front end

apps/pwabuilder/src/script/pages/app-home.ts
Referrer value was being reset when revisiting homepage, it will now persist.
=> Fix: Persist referrer value in sessionStorage across URLs

apps/pwabuilder/src/script/components/publish-pane.ts
fixes #4584 
Feedback messages were persisting when package modal was closed, added a line to clear them out.
=> [FIX] #4584: Dismiss feedback messages when modal is closed

apps/pwabuilder/src/script/components/android-form.ts, apps/pwabuilder/src/script/components/publish-pane.ts
fixes #4382 
Feature
Options in old order 
Options in new order
=> Rearranged Android options

components/code-editor/src/code-editor.ts, components/manifest-editor/src/components/manifest-code-form.ts
Reduce confusion by making code editor read only.
=> Quick Fix: make Code Editor read only

apps/pwabuilder/src/script/utils/icons.ts
=> #4486: FindSuitableIcon grabs last suitable icon, not first.

docs/builder/manifest.md, libraries/manifest-information/src/index.ts
fixes #4635
Replace typo "doucument" with "document"
=> Replaced typo 'doucument' with 'document'

apps/cli/README.md, apps/cli/package-lock.json, apps/cli/package.json, apps/cli/src/analytics/usage-analytics.ts, apps/cli/src/commands/build.ts, apps/cli/src/commands/create.ts, apps/cli/src/commands/start.ts, apps/cli/src/util/campaignUtil.ts
fixes #4728 
Feature 
Whisper starter has been added as a starter option
=> [CLI] Whisper Starter added to CLI

apps/cli/package.json, apps/cli/src/analytics/usage-analytics.ts, apps/cli/src/util/campaignUtil.ts
Changes:
- Track `MessageShow` event with `label` attribute for campaign tracking (like for whisper)
- appended the `version` property to all analytics events to keep track of CLI versioning
=> [CLI] Small analytics update to CLI

docs/index.html, docs/package-lock.json, docs/package.json, docs/styles/global.css
fixes #4750 
fixes #4749 
fixes #4754 
Other... Please describe: Accessibility fixes
Also added typescript as a dependency to fix a build issue with npm start + updated shoelace to the latest version
=> Accessibility fixes

apps/pwabuilder/src/script/pages/app-home.ts
fixes #4743 
Bugfix
When the input was autofilled, the color was a bright blue that did not have good contrast.
It now uses our standard input color.
=> fixes #4743

apps/pwabuilder/playwright.config.ts, apps/pwabuilder/tests/basic.spec.ts, apps/pwabuilder/tests/packaging.spec.ts, apps/pwabuilder/tests/report-card.spec.ts
- Build or CI related changes 
The existing `npm run tests` is using a hardcoded URL mapped to https://preview.pwabuilder.com/reportcard?site=https://webboard.app which isn't working (outdated env variable) and also doesn't help validate **localhost**.
Keep existing setup for CI, and allow localhost sanity check run for devs.
=> fix: playwright tests

components/manifest-editor/src/components/manifest-info-form.ts, components/manifest-editor/src/components/manifest-settings-form.ts, components/manifest-editor/src/components/manifest-share-form.ts
fixes 
#4762
Bugfix
4762 - required fields in manifest editor are not announced as "required" by narrator
4762 - required fields in manifest editor are announced as "required" by narrator
=> Small accessibility push

apps/pwabuilder/src/script/components/android-form.ts, apps/pwabuilder/src/script/services/publish/android-publish.ts
Google Play Console no longer accepts minSdkVersion lower than 23. This change:
- Sets minSdkVersion to 23 in default Android package options
- Maintains minSdkVersion at 23 regardless of Meta Quest status
- Fixes toString() method call in fullScopeUrl generation
This ensures all Android packages meet Google Play Console requirements.
Currently, PWABuilder's CloudAPK service uses a default minSdkVersion of 19, which causes app submissions to be rejected by Google Play Console. Additionally, the minSdkVersion is removed when Meta Quest mode is disabled, potentially causing submission issues.
- minSdkVersion is consistently set to 23 across all Android package generations
- Meta Quest mode changes no longer affect the minSdkVersion setting
- All generated Android packages will be compatible …
=> fix: set minSdkVersion to 23 by default for Android packages

apps/pwabuilder/src/script/services/publish/windows-publish.ts
Bugfix 
Due to an issue in our backend, the packaging process has some issues currently, which we need to fix our deployments to fix. Because of this, the quicker fix is to get a temp front-end fix in.
This will not enable widgets if the app does not actually implement widgets, BUT, by setting this flag, we avoid the broken code on our backend.
=> fix(): temp fix for packaging as we work through backend issues

libraries/manifest-information/src/index.ts
Fix a typo in the tooltip content present in the description for share_target.extra-step.
This pull request will fix a typo in the tooltip content for handling receiving share data in your code within Share Target present within the Edit your manifest modal. The typo is present in the last sentence of the tooltip content, which currently reads:
> You will need to add this scriot to your SW.
This PR will correct the typo to:
> You will need to add this script to your SW.
=> fix(libraries): Update tooltip description for share_target.extra-step

apps/pwabuilder-vscode/src/services/manifest/manifest-service.ts
The popup is:       "PWABuilder Studio will generate your Web Manifest, first, you will need to choose where to save your manifest.json file.", which doesn't read very well.
Clearer grammar
=> clean up wording of vs code manifest creation popup

docs/builder/faq.md
Fixes #4904  - adds documentation for app install source for Android, Windows, and iOS.
No documentation for Windows or Android app launch source.
FAQ doc includes blurb on determining Windows and Android app launch source.
=> Adds Q&As for determining app launch source

docs/builder/store-dot-app.md
This follows [this tweet](https://twitter.com/pwabuilder/status/1747704637774524903). Hopefully this is just the first step of a deeper collaboration between Store.app and PWABuilder.
No mentions of Store.app
Guide the users on how to list their PWA on Store.app as another viable option
See https://github.com/pwa-builder/PWABuilder/issues/4619
=> Add Instructions to Publish PWA on Store.app

apps/pwabuilder/src/script/pages/app-report.ts, apps/pwabuilder/src/script/utils/interfaces.ts
fixes #4553 
Bugfix
When a page has the service worker resource but does not register it properly on the page, the `AuditServiceWorker` request works properly but the page's `Report` request returns that there is no service worker, this generates a race condition and mismatch where it first appears that the page has a service worker and then (with the second request) updates the status to show that no service worker was found.
A warning banner notifies that a mismatch has been found, possibly pointing to an incorrect registration of the service worker.
=> fix service worker registration timeout #4553

apps/pwabuilder/src/script/pages/app-report.ts, apps/pwabuilder/src/script/utils/icons.ts
fixes #4445
Bugfix
For certain pages where the icon configuration has inconsistencies in the manifest. It passes certain sets of tests but fails in the validations executed in the views to generate the packages for the stores.
We leave a [link](https://www.pwabuilder.com/reportcard?site=https://southworks.github.io/paeonia-pwa-app-demo/) to the report of a test page where we play with the configuration of the manifest and we can replicate different scenarios.
We standardized the tests to include the same icon validations that the stores package generation executes when validating the manifest and in case of inconsistencies it blocks the “Package for Stores” button. Where also appears in the Actions Items the detailed error. And in the manifest details a specific check of “Manifest has …
=> add suitable icon validation in manifest tests #4445

apps/pwabuilder/src/script/components/manifest-editor-frame.ts
fixes #4262 
Bugfix
When the manifest modal is opened, it has icons that open a tooltip to give more detail about the field to be filled. If escape is pressed when a tooltip is open, it closes the modal along with the tooltip. When the intention would be that only the tooltip is closed.
When there is a tooltip open in the manifest dialog, and the escape key is pressed, it just closes the tooltip, and in case there is no tooltip open, it closes the dialog as expected.
=> fix unexpected close dialog when a tooltip is open and escape key is pressed #4262

docs/builder/app-store.md
fixes #4877
Documentation for old pod specs did not cover new requirements for use of third-party services
The documentation details the issue and how to fix it by command updating the pod repo
=> Add doc detail related with missing privacy manifest error #4877

apps/pwabuilder/src/script/pages/app-report.api.ts, apps/pwabuilder/src/script/pages/app-report.helper.ts, apps/pwabuilder/src/script/pages/app-report.ts
- #4669 
- Feature
Images described in the manifest are not validated, thus they could not actually exist
/Report tries to fetch (HEAD request with a fallback GET request) images described in the manifest and display package blocking error if they could not
=> validate manifest images exist #4669

apps/pwabuilder/src/script/components/publish-pane.ts, apps/pwabuilder/src/script/utils/indexedDB.ts
- #4609
- Feature
Some store package form inputs have to be manually input, thus needing to take note of previous values in case of new version packaging.
All of the form inputs are stored with the indexedDB API, loading the inputs of previously edited forms. Save occurs on form back, form panel close and submit.
=> Store and load store package form inputs #4609

apps/pwabuilder/src/script/components/android-form.ts
fixes #4312
- Bugfix
.jks files are not supported on the custom signing key file input
added signing support with .jks files
=> support jks in signing key file input #4312

libraries/manifest-validation/src/mani-tests.ts
Issue with `./` type relative URLs in the manifest validation test for `protocol_handlers` updated the test to account for this type of relative URL.
=> updated protocol handler validation

docs/builder/app-store.md
There are a couple of typos along with some inaccurate and outdated information in the file `docs/builder/app-store.md`.
I discovered these while publishing my [PWA](https://www.wordgains.com) to the App Store. The instructions were still incredibly useful! Thank you!
Hope this helps.
List of fixes:
1. `try our your app` -> `try out your app`
2. `Signing & Capabilities` tab is not under xcode -> It is under`Project Navigator` where you select your application.
3. a numbered list had a skipped number
4. `App Store` is now called `App Store Connect` under `Distribution` in step `6. Create a Provisioning Profile`
5. `Preferences` is now called `Settings` on Mac
closes: #4968
=> Update the app store publishing docs

apps/pwabuilder/src/script/components/publish-pane.ts
Fixes an issue where if you set custom values in packaging form, e.g. you set PackageID to something non-default in the Android Form, then closed the form and opened it again, the values in the UI would be set to your new package ID, but the underlying model wouldn't be set to the new value. Thus, the actual Android package you generated would be set to the original value.
This PR fixes that bug.
Bugfix
=> Fixes bug where model state wasn't updated due to input event not firing
