app/styles/_modules/_m-partners.scss

We don't want to show this section on this moment.

Hide partners section for now.

---

app/styles/_modules/_m-generator.scss
app/styles/_modules/_m-infobox.scss
app/styles/app.scss
app/templates/components/download-archive.hbs
app/templates/components/publish-package.hbs
app/templates/generator-steps.hbs
app/templates/index.hbs

Add simple version of step 3

---

app/styles/_components/_c-button.scss
app/styles/_modules/_m-generator.scss
app/styles/_modules/_m-infobox.scss
app/templates/generator-steps.hbs

The last design for pusblish page

Update publish layout

---

app/components/generator-start.js

Add a simple validation to the site url

Add url validation on frontend

---

Brocfile.js

Add uglify when the environment is not development, also remove sourcemaps

Add uglify when is not dev

---

app/templates/index.hbs
app/templates/shared/footer.hbs

fix some links

---

app/components/download-appx.js
app/components/publish-package.js
app/components/upload-image.js
app/models/generator.js
app/routes/generator.js
app/styles/_components/_c-modal.scss
app/styles/_modules/_m-generator.scss
app/templates/components/download-appx.hbs
app/templates/generator-steps.hbs

Initial changes to support adding a button to allow the user to download a complete AppX package to try on their machine or submit to the store.
Corresponding API Changes here: https://github.com/pwa-builder/manifold-api/pull/48
Remaining Items:

[First Draft] Make AppX button Support

---

locales/en.json
pages/_lang/index.vue
pages/_lang/publish.vue
store/index.ts
store/modules/generator.ts
store/modules/publish.ts
store/modules/serviceworker.ts

Reset button functionality in publish page.

Add reset app functionality

---

pages/_lang/serviceworker.vue
store/modules/serviceworker/serviceworker.state.ts

We add a new property to the store to handle the coming soon feature.
We modify the servicesworker.vue file to set a "coming soon" label when the new property disable is true.

Coming soon feature

---

pages/_lang/imageGenerator.vue

Add color picker to image generator custom color

---

store/modules/generator/generator.helpers.ts

New version without using the HTML <a /> element with was breaking automatic testing

Fixing URL parsing for image

---

azure-pipelines.yml
dockerfile
package.json

This PR has a dockerfile file that generates a docker image to preview, prod and dev environment. Also, it has the azure-pipelines.yml script to set up the CI configuration with Azure DevOps. This script uses the environment variables dockerId and dockerPassword to authenticate docker, and the targetVersion environment variable to set the docker stage to target (build-prod, build-preview, and build-dev).

Add dockerfile and pipeline script for CI with DevOps

---

environments/production.js

This reverts commit c1fe5d796af9b677faa5197e7ea830d5df026183.

Revert "target to API in preview" 

---

assets/scss/app.scss

typo prevented server from running correctly on localhost.

fix typo in assets/scss/app.scss

---

README.md

Minor change, just updating obvious placeholder in README.
Thanks!

Replace placeholder link in README with actual link

---

test/store/modules/generator/generator.actions.test.ts

Fix failing generator tests

---

pages/_lang/publish.vue

fixed android missing package

---

pages/_lang/reportCard.vue

Fixes the error message templating and updates the design of the button on error.
Also has a shake animation.

Fix Input Validation on Index Page Error Messages & Design

---

pages/_lang/generate.vue
store/modules/generator/generator.actions.ts

Fix the icons updating when deleted from the generate page

---

assets/scss/base/mixins/_layout.scss
components/CodeViewer.vue
components/HubHeader.vue
pages/_lang/feature/_detail.vue
pages/_lang/features.vue
pages/_lang/generate.vue
pages/_lang/reportCard.vue
pages/_lang/serviceworker.vue

Fixes #
First big pass to fix most of the issues of our responsive design.

Fix responsive

---

nuxt.config.js

fix(): set module type so that code only loads in modern browsers

---

nuxt.config.js

Spartan fix

---

nuxt.config.js

Spartan fix with polyfills

---

pages/_lang/feature/_detail.vue
pages/_lang/publish.vue
pages/_lang/reportCard.vue

Fixing the publish page for responsive + Fixing bugs on layout while navigating
Still need to work on modal window that aren't centered on all resolutions / format

Fixing the publish page for responsive + Fixing bugs on layout 

---

assets/SnippitPop.js
components/Download.vue
components/FeatureCard.vue
components/HubHeader.vue
components/Modal.vue
components/snippitCode.vue
pages/_lang/feature/_detail.vue
pages/_lang/features.vue
pages/_lang/generate.vue
pages/_lang/publish.vue
pages/_lang/reportCard.vue
pages/_lang/serviceworker.vue
static/copyButton.js
static/offline.html
store/modules/generator/generator.actions.ts
store/modules/generator/generator.helpers.ts
store/modules/generator/generator.mutations.ts
store/modules/publish.ts
store/modules/serviceworker/serviceworker.actions.ts

chore(): remove console logs

---

components/Modal.vue
pages/_lang/generate.vue
pages/_lang/publish.vue

Updating CSS for the upload image modal form in Manifest edition and the Android options in Build

Final update for modals

---

package-lock.json
package.json
uitest/index.spec.js

setup ui tests

---

.github/workflows/actions.yml

chore(): update install command

---

components/Download.vue

Start url fix

---

pages/_lang/feature/_detail.vue

Navigating via back button

---

locales/en.json
pages/_lang/generate.vue

Remove specify related applications to be added to the manifest message

---

store/modules/generator/generator.actions.ts
store/modules/generator/generator.state.ts

Fix for an old manifest showing when analyzing a another site

---

components/HubHeader.vue

App's log is being used to load home page than used as a back button

---

pages/_lang/serviceworker.vue
store/modules/serviceworker/serviceworker.actions.ts

Removed push notification's service worker which was added for demo

---

components/HubHeader.vue

Better fix to display the Build Button in portrait mode om mobile

---

pages/_lang/reportCard.vue

This PR enables this new UI for PWAs that score an 80 or above. For PWAs that score lower than 80 they will be shown the traditional experience.

Updated UI flow for PWAs that score 80 or above

---

.github/ISSUE_TEMPLATE/bug_report.md

Other... Please describe: 
Update Feature-request emoji to enable bot operations
Lack of emoji in the instructions does not let the bot add bug label when a new issue is open. 
It will automatically add the bug label when a new issue is filed.

Update feature request emoji

---

locales/en.json
pages/_lang/generate.vue

Remove specify related applications to be added to the manifest message (Recreated #644)

---

pages/_lang/generate.vue

Fixes #
Bug: https://github.com/pwa-builder/PWABuilder/issues/647

Fixed issue related with a manifest shown with manged related_applications

---

pages/_lang/serviceworker.vue

Delay mounting codeViewer component on service worker page for milliseconds to fix concurrency issue

---

components/HubHeader.vue

App's log is being used to load home page than used as a back button (Recreated #646)

---

components/HubHeader.vue
locales/en.json
pages/_lang/generate.vue
pages/_lang/serviceworker.vue

merge dev to prod

---

components/Download.vue

fix(): fixes #673

---

components/CodeViewer.vue
pages/_lang/generate.vue
pages/_lang/serviceworker.vue
store/modules/generator/generator.actions.ts
utils/helper.ts

Fixes #
1) [focus update only on form exit](https://github.com/pwa-builder/PWABuilder/issues/561)
2) [manifest viewer doesn't take full advantage of page space](https://github.com/pwa-builder/PWABuilder/issues/563)
3) [sw screen text gets cut off](https://github.com/pwa-builder/PWABuilder/issues/570)
4) [object object in related apps](https://github.com/pwa-builder/PWABuilder/issues/454)

Bug fix manifest viewer

---

store/modules/generator/generator.helpers.ts

Fixes #630 
- Bugfix 
Cookies are not passed / picked up when trying to access the page
Use credentials: 'include' for the "fetch" operation
Unfortunately this does not work on my build env (even before the change)

Fix #630: Infinite loop when PWA requires Cookie

---

components/HubHeader.vue
pages/_lang/reportCard.vue

Fixes #
Put PWA URL into URL #660 (deeplinking)

Deeplinking pw aurl

---

environments/development.js
environments/preview.js

pointing to the preview API to get the latest service workers. Will point to prod once testing is done and before we push to prod.

feat(): new service workers

---

components/CodeViewer.vue
pages/_lang/serviceworker.vue

Cleaning up this page to make the registration code viewer shorter plus swapping our two code viewers around based on feedback from David.

Service worker page cleanup

---

pages/_lang/generate.vue

Fixes #
https://github.com/pwa-builder/PWABuilder/issues/566

Hide broken images

---

components/ScoreCard.vue

Fixes #
Apps that have names ending with a period break APK generation [#693](https://github.com/pwa-builder/PWABuilder/issues/693)

Remove a specific character like period if it is at the end of the string

---

pages/_lang/features.vue

Fixes the issue where clicking the "authentication" button in the feature store wasn't showing pwa-auth.

Added pwa-auth as member of auth features group

---

components/ScoreCard.vue

Bugfix
There is a missing letter in `Valid SSL certificate is use`.
It reads now `Valid SSL certificate is used`.

fix(): add missing letter

---

components/Download.vue

Fixed error generating signed APK

---

pages/_lang/reportCard.vue

This updates the "get started" button for the starter to a dropdown

Starter drop down

---

pages/_lang/feature/_detail.vue
store/modules/windows/windows.actions.ts

feat(): added inking snippet info

---

components/HubHeader.vue
pages/_lang/reportCard.vue

Feature
Links out to our new demos + components showcase

feat(): link to new features page

---

components/ScoreCard.vue
pages/_lang/reportCard.vue
store/modules/generator/generator.actions.ts
store/modules/generator/generator.helpers.ts

Fixes #761, better handling for HTTP sites.

Better handling of HTTP sites

---

pages/_lang/publish.vue

Capitalize publisher name in UI form for MS Teams package download

MS Teams integration capitalize publisher name

---

components/Download.vue
store/modules/generator/generator.state.ts

Adds support for app manifest shortcuts

Support manifest shortcuts

---

environments/development.js

Changed apiUrl in envrionments/development.js from prod to pre to test the changes deployed to the preview API server for the msteams integration work.

changed apiUrl from prod to pre

---

environments/development.js
environments/preview.js

Fixes #
point to pre for sanity testing.
- Other... Please describe: Preview
Preview is pointing a prod, point it at preview for a short period.
To test new api path

Preview tmp point

---

components/Download.vue
components/Header.vue
package-lock.json
store/modules/generator/generator.mutations.ts
store/modules/generator/generator.state.ts

Fixes #752 by sending in manifest URL to CloudAPK.

Sending manifest url to cloud apk

---

pages/_lang/generate.vue
pages/_lang/manifestGenerator.vue

Checks for analytics before using them.

Added missing checks for analytics

---

pages/_lang/generate.vue
store/modules/generator/generator.helpers.ts
store/modules/generator/generator.mutations.ts
store/modules/generator/generator.state.ts
tsconfig.json

Manifest page is updated to support shortcuts per #752

Manifest page shows shortcuts properly

---

assets/scss/base/_variables.scss
components/CodeViewer.vue
components/ColorSelector.vue
components/FeatureCard.vue
components/HubHeader.vue
components/InstallButton.vue
components/ScoreCard.vue
components/snippitCode.vue
nuxt.config.js
package-lock.json
pages/_lang/feature/_detail.vue
pages/_lang/features.vue
pages/_lang/generate.vue
pages/_lang/publish.vue
pages/_lang/reportCard.vue
pages/_lang/serviceworker.vue

Bugfix 
Accessibility fixes using the AXE extension

Accessibility fixes

---

pages/_lang/generate.vue

Fixes #
CSS issues in carousel
Bugfix

Css for screenshot carousel

---

components/Download.vue
environments/development.js
environments/preview.js
environments/production.js
environments/test.js

Adds CloudAPK preview environment.

Added CloudAPK preview environment

---

pages/_lang/generate.vue
store/modules/generator/generator.actions.ts
store/modules/generator/generator.helpers.ts

Screenshot service

---

pages/_lang/generate.vue
store/modules/generator/generator.actions.ts
store/modules/generator/generator.helpers.ts

Fixes #
Error handling for Invalid Urls and made screenshot size optional on carousel.
Bugfix

Error handling for screenshot urls

---

components/Download.vue
package-lock.json
pages/_lang/publish.vue

Alignment of download button

---

components/Download.vue
pages/_lang/publish.vue
store/modules/generator/generator.actions.ts

Fixes #
PWABuilder Publish page should have PWA's URL to work properly with navigation [#808](https://github.com/pwa-builder/PWABuilder/issues/808)

PWABuilder's Publish page is properly working with navigation

---

pages/_lang/generate.vue

Fixes #
ugly icon generator screen [#565](https://github.com/pwa-builder/PWABuilder/issues/565)

Custom file input styling - from ugly to pretty (New)

---

components/HubHeader.vue

Fixes #820 
Bugfix 
Label was not very descriptive.
The alt-text now fully describes what the image is.

fix(): better alt text for logo

---

locales/en.json

Fixes #853 
Bugfix 
Label did not describe input accurately.
Label is accurate to what the input needs.

fix(): improve label

---

pages/_lang/reportCard.vue

Fixes #819 
Bugfix
We were going from an h1 to an h3.
This PR changes the h3 header to an h2, which is the correct structure.

fix(): correct header structure

---

components/FeatureCard.vue
pages/_lang/reportCard.vue
static/data/featured.json

fix(): feature links

---

pages/_lang/reportCard.vue

- replaced "dont" with "don't" in "Or, dont even have a website yet?" in the report card.
Other... Please describe: Fix typo

Fix typo in report card

---

pages/_lang/reportCard.vue

Grammar Fix
Text on pwabuilder.com appears as: **...Or, dont even have a website yet?**
Text on pwabuilder.com now appears as: **...Or, don't even have a website yet?**

Add apostrophe to the word "dont" 

---

static/offline.html

Fixes #
#852 
Not 100% sure why, but the lang has been added after this small tweak, albeit it doesn't affect the page it is supposed to...
- Bugfix
Add a lang tag (probably for localization efforts in accessibility).
Lang tag added to offline / status code 500 page.

add lang to the offline page.

---

components/ScoreCard.vue

Service working scoring tally fixed

---

pages/_lang/publish.vue

Fixed monochrome icon data binding for Android platform.

Fixed bug in monochrome icon input

---

components/CodeViewer.vue
package-lock.json

Fixes issue where service worker code viewer obscures part of the code

Fixed code viewer sizing

---

assets/scss/base/_globals.scss
components/Download.vue
pages/_lang/publish.vue
pages/_lang/reportCard.vue

Focus outline is now more subtle and less ugly

More subtle styling for button focus outline

---

components/ScoreCard.vue

Fixes #
#814 
- Bugfix
Duplicate id.
Changed the id.

changed id.

---

components/CodeViewer.vue
components/Header.vue
components/ScoreCard.vue
pages/_lang/reportCard.vue

Fixes #
#813 
#821 
#835 
#854

Contrast fixes

---

pages/_lang/reportCard.vue

Fixes #
Bugfix
"View more" link is broken
"View more" link is updated to reference at "https://components.pwabuilder.com/"

Updated "view more" features link

---

pages/_lang/reportCard.vue

Fixes #913 
- Bugfix
When menu loses focus, the menu does not close.
I did not meet a requirement of the accessibility test.
When menu loses focus, the menu closes.

Issue 913 try 2

---

components/ScoreCard.vue

This links the site to our new Azure Functions based web manifest test (repo: https://github.com/pwa-builder/pwabuilder-tests). Currently this does not change what tests we display to the user, but simply changes how we run the tests behind the scenes. However, updating how our tests are done is the first step to implementing the new tests + the new UI for the tests.
Feature 

feat(): use new manifest tests

---

assets/scss/app.scss

Fixes #851 
Bugfix
The error page had a few elements which did not meet the contrast best practices. This PR fixes that.
The color Nuxt uses for the title on the built-in error page is contrasty enough, so this PR just uses that color for the offending elements.

fix(): fixes #851

---

components/ScoreCard.vue
environments/development.js
environments/preview.js
environments/production.js

Feature
This connects the frontend to our new service worker tests, like my PR to connect the new manifest tests. I also did some cleanup and moved the URLs into our environment files. The changes are very minimal as the new test is completely backwards compatible with the old ones.

feat(): use new sw tests

---

components/ScoreCard.vue

Feature
This connects PWABuilder to the first version of our new security tests. This makes our current tests much more accurate as we are now using puppeteers [SecurityDetails API](https://github.com/puppeteer/puppeteer/commit/856c431914f361ab49bef588158370dad7f2f06f) to make the tests. This also, as with the other testing updates I have done, sets us up to add our new tests in my next steps. With this PR, all of the tests on preview will now officially be using the new Azure functions 😊🎉
- [ x] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design) …

feat(): new security tests

---

store/modules/generator/generator.mutations.ts

- Bugfix
Throws an exception for icons and screenshots if the entry dne.
Skips.

entries dne so should escape

---

.github/workflows/docker-publish.yml

fix(): run on pull requests to master

---

components/ScoreCard.vue
store/modules/generator/generator.actions.ts

Fixes #
#921 
#951 
#971 
- Bugfix
- Refactor
Type error was causing an exception, exception block was accessing a missing property in the exception block which wasn't being caught in the function higher above. This caused the javascript execution to stop.
Throws exception, the parent catches the exception. Added refactor as this was a bit tricky to understand what was going on.

New service exception handling changes

---

components/HubHeader.vue
components/ScoreCard.vue
pages/_lang/reportCard.vue

Feature
First part of new store readiness tests + tweaks to the UI to emphasize this.

New test ui

---

pages/_lang/reportCard.vue

Bugfix 
Responsive design is currently broken on mobile
Site is back to being responsive on mobile

fix(): responsive design fix

---

pages/_lang/generate.vue

fix(): change all #main

---

components/ScoreCard.vue
pages/_lang/reportCard.vue
store/modules/generator/generator.actions.ts

Fixes:
- Implements a fallback if our normal manifest detection fails
- If the fallback also fails, this PR adds an event that gets emitted that will allow us to show an alternative UI to the user.
- Improves the loading experience of the test cards
- Uses the improved service worker test that fixes some timeouts we were seeing
Bugfix 

Manifest handling

---

components/ScoreCard.vue
pages/_lang/reportCard.vue
store/modules/generator/generator.actions.ts

* fix(): fallback for manifest detection, improved SW tests, setup for alternative UI for manifest
* fix(): improve test loading experience + vue change detection is annoying
* fix(): improve test loading experience more + change detection fixes
Fixes #

Manifest handling (#1087)

---

environments/development.js
environments/preview.js
environments/production.js
environments/test.js
store/modules/generator/generator.actions.ts
store/modules/generator/generator.helpers.ts
store/modules/generator/generator.state.ts
utils/manifest-fetcher.ts

Adds an HTML parsing service as a fallback for manifest detection.

Added HTML parsing fallback for manifest detection

---

components/ScoreCard.vue
utils/caching.ts

Other... Please describe:
Improvements
Because we were not doing any caching of the data (which was removed a few weeks ago as the old impl was causing bugs) we were calling the tests when not needed during a session.
This PR uses sessionStorage to cache the data from our tests per URL so that the perceived time of the tests is down after the site has been tested at least once during a session. This is the same exact behavior as we used to have, but with a much simpler implementation of the caching mechanism.
- [x ] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/a …

Test caching

---

pages/_lang/reportCard.vue

For an issue mentioned by @davrous

Pwabuilder accessibility 09172020

---

locales/en.json

Fixes #458, grammar bug

---

components/ScoreCard.vue

If our service worker test times out on an app, we currently tell the user that they do not have a service worker, but that may not be the case.
This PR shows a new message if the service worker test 500's:

fix(): show better message if sw test times out

---

components/Download.vue
environments/development.js
environments/preview.js
environments/production.js
pages/_lang/publish.vue

Fixes #
Feature
New Edge platform! Marked as beta for now

feat(): new edge platform

---

components/Download.vue
utils/windows-utils.ts

Bugfix 
If the name of the app had a space in it the package generation would fail, this PR adds a validation function to fix this. This function can also be modified in the future for any more validations needed.

fix(): packageID is validated first

---

pages/_lang/publish.vue
store/modules/publish.ts

Fixes #1113
Adds support for nav bar dark color, nav bar divider color, nav bar divider dark color, and site settings shortcut.

Supports dark mode colors, settings shortcut

---

components/ScoreCard.vue

Fixes #1131 
Bugfix 
There were two things going wrong here: 
First, the code path for sites that use our last fallback was making a POST request to API v2 incorrectly. This PR fixes that by adding the correct request headers.
Second, there were some async issues and then just straight up logic issues with the same code path, I also fixed that.
Finally, this PR also includes formatting fixes from VSCode

Manifest fix

---

components/Download.vue
pages/_lang/publish.vue
store/modules/publish.ts
utils/android-utils.ts
utils/windows-utils.ts

Feature
The current Windows platform on preview does not have the options UI for things like publisher info etc.
This PR adds and connects an options modal for the new Windows platform

New Windows Package options

---

components/ScoreCard.vue

Bugfix 
Scoring was not correct in some cases as our check was not correct. Because of this, the user could only ever score 35 instead of 40.
The manifest name check is now correct in all cases.

fix(): scoring is correct

---

utils/manifest-fetcher.ts

Fixes #
https://github.com/pwa-builder/PWABuilder/issues/1147
https://github.com/pwa-builder/PWABuilder/issues/1079
https://github.com/pwa-builder/PWABuilder/issues/1116
https://github.com/pwa-builder/PWABuilder/issues/1112
https://github.com/pwa-builder/PWABuilder/issues/1108
- Bugfix
If the non v1 api methods get the manifest, it doesn't populate the id and fails to establish the reference in redis for the packaging of apps.
Creates the entry in redis.

Manifest fetcher pass manifest info object redis for v1

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/question.md

Documentation content changes 
Updated the issue and questions templates.

Issue template update

---

components/CodeViewer.vue
pages/_lang/publish.vue
utils/android-utils.ts

Fixes #1160, adds better formatting to error messages, and makes new Windows platform not share error data with Android platform.

Fixes #1160, pwd validation. Better error format.

---

pages/_lang/publish.vue
store/modules/publish.ts

Implements #1151, giving a front-end UI to allow devs to generate an Android package with source code included.

#1151, option to include source in Android package

---

components/ScoreCard.vue

Other...: improves the speed at which the tests finish
We were `await`'ing each test in the created lifecycle event, which meant that the component was waiting on the previous test to finish before starting the others. This causes more delay than is necessary in the tests.
We just let the tests async run and do not `await` them in the created lifecycle event.

fix(): tests finish faster

---

components/ScoreCard.vue

Other...: UX Improvements
Security card did not have the loading experience that the manifest and sw cards do.
Security card has identical loading experience to the other cards

Security card fix

---

pages/_lang/publish.vue
utils/android-utils.ts
utils/windows-utils.ts

Updates the new Windows platform options dialog to include links to documentation. Added more validation on packages.

Updated Windows package options

---

pages/_lang/publish.vue

Addresses #1194, the Windows platform code will prioritize PNG and JPG, and punt when it can't find one, as the Microsoft Store requires PNG or JPG images.

Addresses #1194, Windows pkg requires a PNG or JPG

---

pages/_lang/publish.vue

Implements #1187, ChomeOS-only option for Android platform

Implements #1187, ChromeOS-only option

---

components/ScoreCard.vue

This makes the categories, screenshots, and shortcuts (the least known ones) tests links so that users can quickly see what each one of these is. I was going to make all the manifest tests links, but that muddies up the UI and I'd rather figure out a longer-term solution with our designer. However, I did feel like this was immediately helpful for categories, screenshots and shortcuts as they are the least known.
- [ x] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design). Use tools like https://webhint.io/ to validate …

chore(): links for categories, screenshots and shortcuts

---

pages/_lang/reportCard.vue

Bugfix
There was not an issue open for this, but we saw this when Melanie was going through the site the other day: 
This broke the site when the user would reload on the home page.
Error no longer happens.

Layout issue

---

components/ScoreCard.vue

We were making a call to our current offline test which is not needed anymore since the new Lighthouse based Service Worker test does the offline test for us. This also allowed me to refactor the service worker test code to be a little simpler.
We no longer need to make a separate call to our offline function, so I removed that. This allowed me to simplify that code a bit.

refactor(): remove un-needed offline test + simplify sw score

---

store/modules/generator/generator.mutations.ts

Fixes #
- Bugfix
The property was being unset if missing a property, this gives a second complex case to handle
^^

handle generated icons edge case

---

components/ScoreCard.vue
pages/_lang/publish.vue
store/modules/generator/generator.helpers.ts

update master from dev

---

components/Download.vue
environments/development.js
environments/preview.js
environments/production.js
environments/test.js

- Feature
The current flow uses the MacOS V1 flow.
Use the MacOS V2 service.

PWABuilder MacOS v2

---

environments/development.js
environments/preview.js
environments/production.js
environments/test.js
package-lock.json
package.json
pages/_lang/serviceworker.vue
store/modules/serviceworker/serviceworker.actions.ts

We were calling out to the old API to get our service workers, since we want to move away from this API I created a new app to serve our service workers https://github.com/pwa-builder/pwabuilder-sw-server. This PR connects the front-end to this new server.
This PR also:
- moves more code away from axios to plain fetch
- uses the file-system access API if available, falls back to the way we have always downloaded files if not available (tested in Firefox to triple check this)
Since we want to move away from the old API I created a new app to serve our service workers https://github.com/pwa-builder/pwabuilder-sw-server. This PR connects the front-end to this new server.
- [x ] …

New service worker server

---

components/ManifestScoreCard.vue
components/ScoreCard.vue
components/ServiceWorkerScoreCard.vue
locales/en.json
pages/_lang/reportCard.vue

Fixes issue where editing manifest after analysis brings up empty page.

Edit manifest nav fixed

---

.eslintignore
.vscode/settings.json
src/script/components/resource-hub-cards.ts
src/script/components/resource-hub.ts
src/script/pages/app-home.ts
src/script/utils/breakpoints.ts

- Feature
- Added a util to help write localized breakpoints, might need to extend for modifications to the ranges.
- Resource Hub Styling is more in line with the mock ups (needs work on breakpoints)
- Resource Hub extensible to use on the 'Complete' page.
- Separated card data and html markup generation from actual component, this is just to keep file sizes small and distinguish items that produce purely html versus actual components. Thinking the same might need to be done with the CSS tbh.

V3 Resource Hub Component

---

src/script/components/app-header.ts
src/script/components/content-header.ts
src/script/pages/app-home.ts
styles/global.css

- Updating the responsive styles for the content-header to match the latest designs
- Updating our CSS variables based on the latest designs

Responsive styles

---

.prettierrc.json
src/script/components/resource-hub-cards.ts
src/script/components/resource-hub.ts
src/script/pages/app-index.ts
src/script/utils/breakpoints.ts
styles/global.css

- Feature
- added ability to manipulate the bounds of the breakpoints. defaults to 'both', other options are: 'no-lower' and 'no-upper'.
- added 2 global css values, + formatting?
- resource-hub.ts mobile breakpoint styling
- formatting for resource-hub-cards.ts

V3 resource hub

---

index.html
src/script/components/app-header.ts

- Adds Ionicons
- Start using ionicons in the header
- Sets up the button + menu icon for the mobile navbar

Add ionicons

---

index.html
src/script/services/manifest.ts

Bugfix
- Change ionicons to the recommended URLs based on a console.info log that was getting thrown from ionicons
- url should have a string type

Ionicons fix

---

src/script/components/blog-showcase.ts

- Feature
The component and most of the styles for the blog component.
There might need to be some font size, line height changes.
TODO - Navigation routing logic will require finished.

V3 Blog Showcase Component

---

package-lock.json
src/script/pages/app-about.ts
src/script/pages/app-home.ts
src/script/services/tests/manifest.ts
src/script/services/tests/service-worker.ts
src/script/utils/environment.ts
src/script/utils/interfaces.ts

Feature
- Adds the call needed to test a manifest
- Adds the call needed to test the service worker
Wanted to go ahead and submit these for a review and and then do the security test after. Most of the code here is copy pasted from the current site but you will notice I removed the cache stuff. The reason I did this is because I want to handle this with our service worker now as that will make things much simpler. I will have that service worker change soon after this too.

Kick off tests

---

src/script/pages/app-about.ts
src/script/services/tests/index.ts
src/script/services/tests/service-worker.ts

Fixes #
Bugfix
Feature
This PR:
- fixes a TypeScript issue
- adds a new runAllTests function that runs the tests concurrently and then resolves a single promise

fix(): typescript issues + runAllTests

---

src/script/pages/app-about.ts
src/script/services/tests/security.ts
src/script/utils/interfaces.ts

Feature
Add Security test just the manifest and service worker tests I added yesterday.

feat(): add security test

---

src/script/pages/app-about.ts

I was using an `any` where I could have been more strict.
Uses the correct type (PointerEvent) intead of `any`

chore(): stricter typing

---

src/script/pages/app-testing.ts
src/script/services/manifest.ts

Fixes #
Bugfix 
This PR:
- uses the correct headers for the fetchManifest call
- uses our new large font size variable for the testing page

Various fixes

---

src/script/components/app-card.ts
src/script/components/blog-showcase.ts
src/script/components/resource-hub.ts
src/script/pages/app-home.ts
src/script/utils/css/hidden.ts

- Feature
- moved card specific styles to app card, structural css in the parent still
- need to keep a button separate from the app-button component for some styling specific stuff that wasn't changeable with the nested button.
- slight refactor
- created hidden class snippets for reuse

Demo Page Cards

---

src/script/components/app-header.ts
src/script/pages/app-home.ts
styles/global.css

<Refactoring (no functional changes, no api changes) 
Font sizes + home page usage of content-header has changed in the design.
Updates font sizes and home page usage of content-header

styles(): font size updates + home content header does not have hero-p

---

src/script/pages/app-home.ts
src/script/utils/interfaces.ts
styles/error-styles.css
styles/global.css

Feature
Adds error states for inputs and applies it to the URL input on the home page.

feat(): url error state + error message

---

src/script/components/manifest-options.ts
src/script/pages/app-report.ts

- Feature
Just the html for the manifest, no styles, no js logic

V3 Report Card - Manifest

---

src/script/components/app-header.ts
src/script/components/app-sidebar.ts
src/script/components/content-header.ts
src/script/pages/app-index.ts

Fixes #
* Added: Layout to handle sidebar component & app-header to Index page
* Removed: app-header from content header component
* Edited: app-header layout to handle fixed position
- Some style got changed in the app-header I don't know if they were wrong before (might need help with vs-code setup if they are wrong)

Added: Sidebar Layout

---

src/script/pages/app-publish.ts
styles/global.css

Finalized the layout + styling of the publish page based on the latest designs and work Harmann had already done.

chore(): finalize publish page layout

---

src/script/components/app-button.ts
src/script/components/dropdown-menu.ts
src/script/components/manifest-options.ts
src/script/components/report-card.ts
src/script/components/score-results.ts
src/script/components/tooltip.ts
src/script/pages/app-report.ts
src/script/services/manifest.ts
src/script/services/tests/service-worker.ts
src/script/utils/hasChanged.ts
src/script/utils/url.ts
styles/global.css

- Feature
- Added checks for changes in arrays and objects (the event loop comparator is shallow).
- Added a simple url resolve mechanism for images... not perfect probably need some validation steps and etc.
- Style changes to app button and the menu
- Moved tool tip function
- Tooltip hover functionality
- Modal
- API functionality

V3 manifest

---

assets/images/active-cell.svg
assets/images/green-tick.svg
src/script/components/app-sidebar.ts
styles/global.css

Fixes #
* Improved desktop sidebar layout
* Added tablet layout
* Added color global variables
* Removed SVG icons and used ion-icons instead
* Added dynamic way to handle steps classes

Improved sidebar & added tablet design

---

src/script/services/icon_generator.ts
src/script/utils/api.ts
src/script/utils/download.ts

- Feature
- port the icon generator and the generate missing images calls.
- util to unify the download experience.
- util to help keep all of the urls in the same place, let me know your thoughts.

V3 Downloads, start on Icon and Image Generator, utils galore

---

src/script/components/app-sidebar.ts
src/script/pages/app-home.ts
src/script/services/app-info.ts
src/script/services/tests/index.ts
src/script/utils/interfaces.ts

Feature
This PR does the following: 
- Refactors how the sidebar works and the styles are applied
- Adds the code needed for the sidebar to understand the current progress.
- Expands on our app-info service to include the data we need. This was just for the sidebar, but this code will also be needed for the base package and congrats page

Sidebar works

---

package.json
src/script/components/app-card.ts
src/script/components/app-file-input.ts
src/script/components/app-modal.ts
src/script/components/app-sidebar.ts
src/script/components/manifest-options.ts
src/script/components/report-card.ts
src/script/components/resource-hub-cards.ts
src/script/components/resource-hub.ts
src/script/components/score-results.ts
src/script/components/sw-picker.ts
src/script/pages/app-home.ts
src/script/pages/app-report.ts
src/script/polyfills/css-paint.ts
src/script/services/app-info.ts
src/script/services/icon_generator.ts
src/script/services/publish/android-publish.ts
src/script/services/service_worker.ts
src/script/services/tests/index.ts
src/script/services/tests/manifest.ts
src/script/services/tests/service-worker.ts
src/script/utils/download.ts
src/script/utils/hasChanged.ts
src/script/utils/interfaces.ts
src/script/utils/url.ts

- Refactoring (no functional changes, no api changes)
- Build or CI related changes
- Just a cleanup, some areas that might need tweaking based on new changes.
- @jgw96 Missing one from the service_worker file, where the error handler isn't based on the fetch and the fs access api document doesn't seem to discuss the shape, so could you write an interface for that one?

no more build errs

---

src/script/services/tests/service-worker.ts

Bugfix 
Tests were stalling on https://github.com (just an example, it would fail with other sites too) because the offline check would time out (expected). If this does time out, we should just return false.
We now return false along with our standard console warn too.

fix(): if the offline check times out return false

---

src/script/services/tests/service-worker.ts
src/script/utils/interfaces.ts

Remove scope as a test after our discussion yesterday. Because scope technically does not have an invalid value and is not changed often from the default we are removing it as a check for v3.

chore(): remove scope as a check

---

src/script/services/tests/service-worker.ts
src/script/utils/interfaces.ts

Fixes #
https://github.com/pwa-builder/PWABuilder/projects/3#card-55709933
Feature
We were not testing for background sync and we were also using an extra call for the perioidic sync check.
This PR updates the code to use the new object that the SW test returns to do both the periodic sync and the new background sync checks, both optional as we discussed.

Background sync

---

src/script/components/report-card.ts
src/script/pages/app-publish.ts
src/script/services/publish/android-publish.ts
src/script/services/publish/windows-publish.ts

Bugfix
Feature
This PR fixes a small layout problem where the package button was not aligned correctly.
This PR also implements a small feature (that also acts as an extra fallback for package generation) where the publish page can work off a query string like so `/publish?site=https://my-pwa.app` , allowing deep-linking straight into the publish page.

Publish query

---

components/Download.vue
components/ManifestScoreCard.vue
components/ServiceWorkerScoreCard.vue
store/modules/generator/generator.actions.ts
store/modules/generator/generator.mutations.ts
store/modules/generator/generator.state.ts
utils/manifest-fetcher.ts
utils/service-worker-checker.ts

- Fixes #1510 by removing Redis sync, solving a whole host of manifest issues.
- Updated service worker detection to use the periodic sync result in the single sw detection call, rather than as a separate call.
- Fixed web package bug when screenshots was falsey.

Removed redis sync.

---

src/script/pages/app-testing.ts

Fixes #
Bugfix
Right now the testing page is not the correct height on screens bigger than an ipad which causes that page to scroll when it shouldn't. 
This PR uses better CSS to ensure that the testing page is always the right height. Tested thoroughly with devtools.

Test page responsive

---

package-lock.json
src/script/components/report-card.ts
src/script/pages/app-basepack.ts
src/script/pages/app-index.ts
src/script/pages/app-report.ts
src/script/services/app-info.ts
src/script/services/manifest.ts
src/script/services/service_worker.ts
src/script/services/tests/manifest.ts
src/script/utils/interfaces.ts

Bugfix
Feature
This PR has two parts:
- A small bug with apps that do not have a manifest stalling on the testing page was fixed
- Implements the first part of the base package page work: page itself and route are added and the first bit of the logic to decide where to send the user.

Base package

---

src/script/pages/app-basepack.ts
src/script/services/manifest.ts
src/script/services/publish/web-publish.ts
src/script/utils/environment.ts

Feature
This PR finalizes the UI that was just stubbed out in the previous PR and adds the code for the API call to generate a web package along with some of the modals for some of the error handling and downloading. This one should only be merged after https://github.com/pwa-builder/PWABuilder/pull/1533

Base package continued

---

src/script/pages/app-basepack.ts
src/script/services/manifest.ts
src/script/services/publish/web-publish.ts

Fixes #
Feature 
This PR implements: 
- Generating a manifest ONLY for sites that do not already have a manifest. This call is not even made if a site already has a manifest. This is an improvement from v2 where we were always generating a manifest even if the site already had one, we just weren't using it after making the call.
- Make sure the base package page can grab the correct manifest
- Mobile styles for the base package page
- [ x] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design). Use tools like https://webhint.io/ to validate your …

Finalize layout, styles and functionality for the base package page

---

pages/_lang/publish.vue

Other... Please describe
Removing the deprecated Legacy Edge platform. This only removes the UI but does not attempt to refactor the code to remove all the legacy Edge stuff as I figured that was more "dangerous" than worth it. 

chore(): remove deprecated legacy edge platform

---

src/script/pages/app-publish.ts
src/script/services/publish/android-publish.ts
src/script/services/publish/index.ts
src/script/utils/environment.ts

Fixes #
Bugfix
Generating Android Packages was busted on v3.
This fixes the android package generation and also fixes a small bug with error handling (a modal that should get closed was not getting closed and therefore was hiding the error modal)

Android fixes

---

.github/workflows/deploy_web_app.yml

Fixes #
I had specified this action to only run on the express branch so that I could easily test this safely without risking breaking anything. 
Now that this has been tested and is working fine I am updating this action to run on the v3 branch.

chore(): run action on v3 branch

---

src/script/components/app-sidebar.ts
styles/global.css
styles/layout-defaults.css

Fixes #
Other... Please describe: css styles update
This PR updates the sidebar itself (not the components within the toolbar, that work will happen separately between Leo and I as discussed this morning) to match the latest design.

styles(): update sidebar container to latest design

---

src/script/components/app-sidebar.ts

Fixes #
Other... Please describe: Style updates
More updates to the sidebar to match the latest design

style(): remove lines + correct margin

---

src/script/components/app-sidebar.ts

Formatting + final style tweaks

chore(): cleanup

---

src/script/components/report-card.ts
src/script/components/score-results.ts
src/script/pages/app-report.ts
styles/global.css

Other... Please describe:  Style and design updates.
This is the start of the design updates for the report-card page and includes:
- scores are displayed the new way with no max score
- scores are based off 10 per thing, not 5
- margin and padding updates across screens sizes
- corrected grids on mobile devices
- updated DOM structure to match the latest design
- removed un-needed borders
- removed un-needed text
- formatting updates
- misc responsive design fixes
This PR does not include:
- color updates on the report card page
- badges 
These two items will be covered in a future PR.
- [x ] Ensure that your contribution follows …

fix(): style updates and fixes based on latest design

---

src/script/components/app-sidebar.ts
src/script/components/report-card.ts
src/script/components/sidebar-card.ts
src/script/pages/app-home.ts
src/script/pages/app-publish.ts
src/script/services/app-info.ts
src/script/services/manifest.ts
src/script/services/tests/manifest.ts
src/script/utils/error.ts
src/script/utils/icons.ts

Fixes #
Bugfix
This PR fixes a few things I found while testing the site this morning, completes some to-dos, css tweaks to match the latest design and brings in the error reporting stuff from v2 into the new error modal. Each fix/improvement is split up by commit below if you are looking for more detail.

Various fixes and improvements for v3

---

pages/_lang/publish.vue
store/modules/publish.ts
store/modules/serviceworker/serviceworker.actions.ts

Fixes #1622, #1620, #1614, #1598, #1561, and numerous others.

Updates Samsung UI to reflect new behavior

---

src/script/components/app-card.ts
src/script/components/app-sidebar.ts
src/script/pages/app-congrats.ts

- Bugfix
Fixes most of the blog card changes and centers the score element

Design Review - Score Centering and Blog Card changes

---

src/script/components/app-header.ts
src/script/components/content-header.ts
src/script/components/report-card.ts
src/script/components/sidebar-card.ts
src/script/pages/app-basepack.ts
src/script/pages/app-congrats.ts
src/script/pages/app-home.ts
src/script/pages/app-index.ts
src/script/pages/app-publish.ts
src/script/pages/app-report.ts
src/script/pages/app-testing.ts

Other... Please describe: Design review changes
This PR fixes multiple issues that were uncovered in design review 3 with Melanie:
- The collapsible cards in the sidebar had a small double border on the bottom when collapsed. I removed some now un-needed css to fix this
- The icons in the header should be white (as they are against a dark background) on tablet-portrait sizes and smaller
- The background should be purple on wide screens with a max-width on the main content 
- [x ] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design). Use tools like …

J design rev

---

src/script/components/app-sidebar.ts
src/script/components/content-header.ts
src/script/components/rating-dial.ts
src/script/components/report-card.ts
src/script/pages/app-home.ts
src/script/pages/app-report.ts
styles/global.css

Other... Please describe:  Design review updates
This PR fixes the following from the last design review:
- line-heights and bottom margins on headers are now correct
- padding is correct and matches for each section of the report-card page
- badge text size + margins are correct
- Update colors and apply the right one to the sidebar

Design rev 2

---

src/script/services/tests/service-worker.ts

Related
https://github.com/pwa-builder/PWABuilder/pull/1660
Bugfix 
This PR ports the new offline check code from v2 to v3

chore(): new offline detection code from Judah

---

package-lock.json
package.json
src/script/pages/app-index.ts
src/script/utils/url.ts

Bugfix
Jeff gave me a bug where if you try just `microsoft.com` (no www, no https etc) the current code would fail and say this URL cannot be reached.
Our "cleanUrl" function now handles this situation correctly. 
NOTE: I also removed an old un-needed import.

Url formatter

---

src/script/pages/app-index.ts

Bugfix
This PR:
- Fixes an issue where the report-card page was not being lazy loaded when it should have because of a missing async import.
- Standardizes the style of the async imports for code consistency

fix(): route import path standardized

---

src/script/components/manifest-options.ts
src/script/components/report-card.ts
src/script/components/resource-hub-cards.ts
src/script/components/score-results.ts
src/script/components/sw-picker.ts
src/script/pages/app-basepack.ts
src/script/pages/app-congrats.ts
src/script/pages/app-home.ts
src/script/pages/app-publish.ts
src/script/pages/app-report.ts

Other... Please describe: Updating text throughout the site
Just updated the text.

chore(): update all lorem text

---

src/script/components/app-badges.ts
src/script/components/content-header.ts
src/script/components/loading-button.ts
src/script/components/report-card.ts
src/script/pages/app-basepack.ts
src/script/pages/app-congrats.ts
src/script/pages/app-publish.ts
src/script/pages/app-report.ts
styles/layout-defaults.css

Other... Please describe: Style changes
This PR fixes the following items from the last design review:
-  sidebar size update to match the latest design
- remove badge text on the badges component
- 2 column down to 1 column on mobile for publish and congrats
- padding and margins on pages
- The "start" button is now correct on mobile
There are a few more fixes coming based on the last items from the design review in my next PR, but wanted to go ahead and get the first chunk out.
- [x ] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design). Use …

Design review 4: Pass 1

---

src/script/components/app-sidebar.ts

Other... Please describe: Style updates based on last design review (design review 4).
The sidebar on tablet sized devices did not match the latest design.
The css has now been updated so that the sidebar looks correct on tablets. My next PR will also fix this for mobile.

fix(): toolbar is correct on tablets

---

src/script/components/app-button.ts
src/script/components/app-card.ts
src/script/components/code-editor.ts
src/script/components/loading-button.ts
src/script/components/manifest-options.ts
src/script/components/tooltip.ts
src/script/pages/app-congrats.ts
src/script/utils/codemirror.ts
src/script/utils/events.ts
styles/global.css

- Bugfix
- Using a throttled resize for app-cards that need to change their styles.
- lots of css variables added and some style changes.
- bugfix for updating a manifest that is edited poorly

V3 Miscellaneous Bug fixes p2

---

src/script/components/app-sidebar.ts
src/script/pages/app-report.ts

Feature
The toolbar was not being shown on mobile.
The toolbar now shows on mobile and it matches the latest design.

feat(): mobile toolbar matches design

---

src/script/pages/app-publish.ts

Fixes #
Feature
The Samsung card was just a placeholder.
The Samsung platform now has the same UI as in V2.

chore(): new samsung modal

---

package-lock.json
package.json
src/locales/index.ts
src/script/components/android-form.ts
src/script/components/app-gallery.ts
src/script/components/windows-form.ts
src/script/pages/app-home.ts
src/script/services/app-info.ts
src/script/services/badges.ts
src/script/services/icon_generator.ts
src/script/services/manifest.ts
src/script/services/publish/android-publish.ts
src/script/services/publish/index.ts
src/script/services/publish/windows-publish.ts
src/script/services/screenshots.ts
src/script/services/service_worker.ts
src/script/services/tests/service-worker.ts
src/script/utils/android-validation.ts
src/script/utils/css/breakpoints.ts
src/script/utils/customMerge.ts
src/script/utils/download.ts
src/script/utils/events.ts
src/script/utils/manifest-validation.ts
src/script/utils/win-validation.ts
tsconfig.json

Fixes #
Other... Please describe: TypeScript fixes
We have various typescript warnings / errors to go through + there was some unused code and code that could be simplified without changing the functionality.
This PR fixes:
- various typescript warnings and errors
- Removes some unused methods, imports and variables (showing as unused in vscode)
- Simplifies the download method for the icons to use the browser-fs-access library
- [x ] Ensure that your contribution follows [standard accessibility …

Typescript fixes and other various small fixes for production readiness

---

src/script/components/manifest-options.ts
src/script/components/report-card.ts

Fixes #
Other... Please describe: CSS Fixes
The manifest editor had a few things that did not match the design such as:
- divider colors
- score was still showing
- button alignment
- widths / margins
All of the above has been updated.

fix(): manifest editor tweaks to better match design

---

src/script/components/manifest-options.ts

Bugfix
We were trying to call a method on a value that may not exist.
We now check for the existence of the value before trying to call methods on it.

fix(): check for existence of item.entry first

---

src/locales/en_US.json
src/script/pages/app-basepack.ts

Other... Please describe: Just a text update
Updated some text that was missed in our last text update. Also went ahead and moved it to our locales object too.
Updated the text and moved the string to locales.

chore(): update text on the test package download modal

---

src/script/components/report-card.ts
src/script/components/windows-form.ts
src/script/services/app-info.ts
src/script/services/publish/index.ts
src/script/services/publish/windows-publish.ts

Fixes #
Bugfix 
The publish page was not working correctly as it did not have the manifest data needed. Turns out this was due to us not `awaiting` some methods that had been updated to return promises.
I have updated the code to properly await methods.

fix(): handle promises correctly

---

src/script/components/app-modal.ts

Fixes #
Other... 
Added our terms of usage link to the modals as requested internally.

fix(): add terms of service to modals

---

src/script/services/icon_generator.ts
src/script/services/screenshots.ts

Fixes #
- Bugfix
The network response returns a promise, so it breaks the flow.
Unwrap the promise.

Fix manifest icons

---

src/script/pages/app-basepack.ts
src/script/pages/app-congrats.ts

Fixes #
Bugfix
Content and headers were not aligned correctly on the base package page (as pointed out in ADO) and also the congrats page (found by me lol).
Content and headers are now aligned on both pages.

fix(): headers are aligned correctly

---

src/script/components/sw-picker.ts

Fixes #
Other... Please describe: User Experience update
After review, it was found that the wording on the Service Worker picker was not very clear
as to what the next steps were.
I have updated the UI with the wording changes discussed this morning.

fix(): update wording on the sw-picker page to be more clear

---

index.html
manifest.json

Fixes #
Other... 
Titlebar was not the expected color.
I have updated the manifest and index.html to make sure that the titlebar is the color we expect (which from the discussion in teams sounded like the background color of the site, which is #FFFFFF)

chore(): update colors for titlebar and splash

---

src/script/pages/app-testing.ts

Fixes #
Other... Please describe: UX Update
Added a few more phrases to the phrase pager on the testing page. This will keep the pager going for longer (and be more informational to the user) which should atleast slightly improve the waiting experience on longer loading sites. Melanie and I will obviously update the waiting page more intensely, but I wanted to go ahead and get this small update out.

Testing page update

---

src/script/components/code-editor.ts

Fixes #
Feature
We did not have a copy manifest button as we did in V2. This was pointed out as a missing item in a review and it was decided that we should add this back.
I have now added this feature to the manifest editor. It will use our standard `disabled button` colors and the text changes to "Copied" after the user has tapped the button. I also figured out that Safari has supported the Clipboard API for a few versions now (well, atleast the basic writeText method we need here), so we do not need a fallback.
* Note: The view-code bar in the screenshots currently has some width challenges on certain size screens, I will fix this up in a seperate PR. I did not update this in this PR as it is unrelated code.
- [ x] Target …

feat(): bring back copy manifest button

---

src/script/components/manifest-options.ts
src/script/pages/app-report.ts
src/script/services/regex.ts
src/script/utils/manifest-validation.ts

- Bugfix
- Network call corrections, currently the service is not receiving fetch call inputs as being correct. This is being investigated as it could be one of two things: 1. CORS prevents local host. 2. Express is not receiving the correct content type (fetch is refusing to set it within the browser context) insomnia works properly.
- investigate that double click issue (caused by event bubbling from text, cannot intercept from within the component, might need to add to the handling logic.).
- The urls passed needed to contain a protocol
- something broke which prevented correct urls from being submitted
- uses regex to parse and validate urls (still allows for bad input potentially)
- enable and disable interactions the same for the add and generate links

V3 Screenshots interaction fixes

---

src/locales/en_US.json
src/locales/index.ts
src/script/components/manifest-options.ts

Keep strings in one place for easy localization
- Code style update (formatting)
- Refactoring (no functional changes, no api changes)
N/A
N/A

V3 Manifest Migration

---

src/script/components/windows-form.ts

Fixes #
Other... Please describe: tiny update
Placeholder was not very clear.
Placeholder is a legit package id.

chore(): better placeholder

---

src/script/pages/app-home.ts

Fixes #
Other... Please describe: Text update
Updated the placeholder for the start input on the home page to hopefully make intended use even more clear.

chore(): update start input placeholder

---

src/script/pages/app-home.ts

Fixes #
Bugfix
Whitespace was not being trimmed from the URL input, leading to potential bugs as David found this morning.
We now trim the whitespace from the URL input.

fix(): trim whitespace from the url input

---

src/script/components/app-badges.ts

Fixes #
Other... Please describe: Small style update
Even lower opacity on a locked icon so it is more distinguishable from an achieved icon.

chore(): lower opacity of locked icon

---

src/locales/en_US.json
src/script/pages/app-basepack.ts

Fixes #
Text updates to the base_package page as requested by the team and specified by Melanie. Also added links to documentation + a documentation button as recommended by Melanie.

chore(): base package text updates

---

package-lock.json
src/script/components/app-header.ts
src/script/components/resource-hub-cards.ts
src/script/components/resource-hub.ts
src/script/components/tooltip.ts
src/script/components/windows-form.ts
src/script/pages/app-congrats.ts
src/script/services/blog.ts

Fixes #
Injecting the final links to blog, docs & demos + fixing some target="_blank" for the tooltip.
Links updates

Integrate final blog doc links

---

src/script/components/android-form.ts
src/script/components/code-editor.ts
src/script/components/manifest-options.ts
src/script/components/sw-picker.ts
src/script/components/windows-form.ts
src/script/pages/app-basepack.ts
src/script/pages/app-congrats.ts
src/script/pages/app-home.ts
src/script/pages/app-publish.ts
src/script/pages/app-report.ts
src/script/pages/app-testing.ts
src/script/utils/analytics.ts

Fixes #
Bugfix 
capturePageAction calls were not completing succesfully.
Removing these calls for now to re-visit post v3

chore(): remove capturePageAction calls

---

src/script/pages/app-congrats.ts

Fixes #
Other... Please describe: Just updating a link
Link was pointing to the old blog.
Now pointing to the new blog.

chore(): update link

---

src/script/utils/environment.ts

Fixes bug where v3 is pointing to non-production API resources.
Bugfix

Pointing to production resources

---

src/script/services/publish/android-publish.ts

Additional fix for maskable images.

Tiny fix for maskable images

---

README.md

Fixes #
Other... Please describe: Readme Update
Updated readme with latest info + production live url

chore(): small readme update

---

src/script/components/cookie-banner.ts
src/script/pages/app-index.ts

Fixes #
Feature
Porting the cookie banner over from v2 
Using the styles from the footer modified slightly. Love the Figma stuff Melanie put together to make things like this easy.

feat(): port cookie banner from v2

---

src/script/components/android-form.ts
src/script/components/windows-form.ts

Fixes #
Same as this PR https://github.com/pwa-builder/PWABuilder/pull/1875 but for the Android form. There is some work that could be done here to use an Abstract class to remove some code duplication but saving that for later so we can get this out now. 
Also did some code formatting. This was tested the same as the Windows PR.

Android form

---

src/script/components/android-form.ts
src/script/components/sidebar-card.ts
src/script/services/publish/android-publish.ts

Fixes https://github.com/pwa-builder/CloudAPK/issues/78 , where URLs relative to the manifest weren't properly resolved.
Bugfix

Android relative url

---

src/script/services/publish/web-publish.ts

bug: base url removed with refactor to only support form.

---

src/script/pages/app-index.ts
src/script/pages/app-publish.ts
src/script/pages/portals-publish.ts

Fixes #
Feature
This is the initial version of the portals page! This has been built to the spec provided by the portals team and I am collaborating with them on testing. This PR specifically does:
- Adding a route for the portals page (so the code is separate from the normal publish page and also as the portals team wanted)
- Initial implementation of the portals page
- Removed one un-used piece of code
*Note* Merging this PR does not affect any "user facing" pages, all of the new things are in a new page that will only be navigated too (really deeplinked into) by the portals stuff, so it should be very safe to merge.
- [x ] Ensure …

Portals V0

---

src/script/components/app-modal.ts
src/script/pages/app-publish.ts
src/script/pages/portals-publish.ts
src/script/services/publish/windows-publish.ts
src/script/utils/error.ts

Fixed an issue that prevented users from "reporting a problem" when the error message was too long due to stack trace.

Cleaned up Windows platform error handling

---

src/script/services/publish/android-publish.ts

Addresses the front-end requirements for #1926
Bugfix

Fix() Data-URL encoded manifest URLs supported in front-end

---

src/script/components/manifest-options.ts

Fixes #
Bugfix
The user was not able to modify their manifest from the code editor itself, only from the form inputs
The user is now able to modify their manifest from either the code editor or the form inputs.

Editor to options

---

src/script/components/windows-form.ts

Fixes #
https://github.com/pwa-builder/pwabuilder-windows10/issues/49
- Bugfix
https://github.com/pwa-builder/pwabuilder-windows10/issues/49
https://github.com/pwa-builder/pwabuilder-windows10/issues/49
- [ V ] Target master branch (or an appropriate release branch if appropriate for a bug fix)
- [ V ] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design). Use tools like https://webhint.io/ to validate your changes.

Fix a validation bug for Windows Package ID with dash character.

---

src/script/components/app-file-input.ts
src/script/components/manifest-options.ts
src/script/utils/interfaces.components.ts

- Bugfix
- Refactoring (no functional changes, no api changes)
Didn't clear input before.
Clears input.

Upload File Modal UX changes

---

src/script/pages/app-publish.ts
src/script/services/publish/android-publish.ts
src/script/services/publish/index.ts

Feature / enhancement
When publish page hits an error generating a package, we show the error message in a bad format: centered text, not horizontally scrollable, whitespace formatting (e.g. new lines) is lost. 
Additionally, we had superfluous try/catch blocks that did nothing but add "Error: {message}" info, resulting in wildly superfluous error messages to the user, such as "Error: Error generating android package: Error: Error generating Android package. Error: [details]".
Finally, we have no special handling for increasingly common 403 errors where Cloudflare blocks bots from accessing sites. 
Better error styling, better error formatting, smarter handling of 403 errors.

Better publish error handling

---

src/script/components/manifest-options.ts
src/script/services/screenshots.ts

- Bugfix
- Screenshots do to trigger a rerender. Change part of the impl so that it will, similar to the icons changes.
- Screenshots display.
tested:
- www.pwabuilder.com
- www.example.com
- webboard.app
- partyfavorz

screenshots bug

---

src/script/components/app-sidebar.ts
src/script/components/cookie-banner.ts
src/script/components/manifest-options.ts
src/script/components/report-card.ts
src/script/components/score-results.ts
src/script/components/sidebar-card.ts
src/script/components/sw-picker.ts
src/script/pages/app-about.ts
src/script/pages/app-basepack.ts
src/script/pages/app-publish.ts
src/script/pages/app-report.ts
src/script/services/app-info.ts
src/script/services/badges.ts
src/script/services/congrats.ts
src/script/services/manifest.ts
src/script/services/publish/index.ts
src/script/services/service_worker.ts
src/script/services/tests/index.ts
src/script/services/tests/manifest.ts
src/script/utils/decorators.ts
src/script/utils/url.ts

Fixes #
Other... Please describe: Developer Experience
We had tons of old console logs that should be removed.
The un-necessary console logs have been removed.

chore(): cleanup code by removing un-needed console logs

---

src/script/components/manifest-options.ts
src/script/pages/app-basepack.ts
src/script/services/publish/web-publish.ts

Changes icons in manifest editor to reflect their actual sizes. Melanie-approved. ☺

Manifest editor tweak

---

src/script/components/manifest-options.ts

Other... Please describe:
Hiding the manifest previewer until LT approval.
The previewer is now live on the website.
Temporarily hiding the component.

Remove previewer

---

README.md

chore(): add a link to the wiki in the readme

---

src/script/components/manifest-options.ts
src/script/utils/icons.ts

This reverts commit 84041d87dff1a4d912747e05566776cfa777ade7.
Fixes #
I broke icons loading for sites that already have icons.
Other... Please describe: revert
This reverts my commit that broke things.

Revert "fix(): check if icon actually loads before we try to display it"

---

src/script/components/manifest-options.ts

Bugfix
The fields in the manifest options form are in lowercase.
The casing is the one indicated on the manifest.

Fix lowercasing of fields in manifest form

---

package-lock.json
package.json
src/script/components/manifest-options.ts

Feature
The manifest previewer is currently commented out in the code.
The previewer has been added to the manifest options form, with only the Windows preview enabled.

Uncomment previewer

---

src/script/components/manifest-options.ts

Hopefully we get a preview of the previewer this time.

 Try previewer deploy again

---

package-lock.json
package.json
rollup.config.js
src/script/pages/app-index.ts

Could not easily tell the version of a build.
This PR adds a rollup plugin that prints out A) The version specified in our package.json and the more useful aspect B) prints out the date and time of the build that is currently running in your browser console.

chore(): add build date and version to console.log

---

src/script/components/hover-tooltip.ts
src/script/components/tooltip.ts

Bugfix 
Because of how the tooltip content was positioned, the hover target for the tooltips was pretty small, leading to it disappearing unexpectedly sometimes.
The tooltips are now positioned in a way that makes the hover target much larger, making it much easier to click on the tooltip link itself.

Tooltips tweaks

---

src/script/services/publish/windows-publish.ts

No padding by default for Windows apps. Request by Windows management.

No padding by default

---

src/script/components/app-header.ts

Fixing 2 of an internal accessibility ADO bugs 35224253 & 35224479
Missing aria label and wrong logo description
Aria-label & logo description fixed

Fixing accessibility bugs 35224253 & 35224479

---

package-lock.json
package.json

Other... Please describe: Dependency update
- Updated to lit 2.0 stable

chore(): update to lit 2.0 stable

---

src/script/pages/app-home.ts

Increased Safari timeout hack

---

src/script/components/app-button.ts
src/script/components/app-card.ts
src/script/components/app-footer.ts
src/script/components/app-header.ts

Fixing 35224253 & 35224732 accessibility bugs

Fixing 35224253 & 35224732 accessibility bugs

---

src/script/components/android-form.ts
src/script/services/manifest.ts

fix(): fix some type issues

---

src/script/pages/app-publish.ts

Other... Please describe: spelling fix

fix(): spelling error on Android modal

---

src/script/components/android-form.ts
src/script/components/ios-form.ts
src/script/components/windows-form.ts

App name special character filter

---

src/script/pages/app-testing.ts

Header and cookie header overlapping on loading page fix

---

src/script/services/tests/index.ts

By safely resolving test values during analysis.
Bugfix

Safe resolution during progress update

---

package-lock.json
src/script/components/android-form.ts
src/script/components/app-package-form-base.ts
src/script/components/ios-form.ts
src/script/components/tooltip.ts
src/script/components/windows-form.ts
src/script/pages/app-congrats.ts
src/script/pages/app-publish.ts
src/script/pages/portals-publish.ts
src/script/services/app-info.ts
src/script/services/blog.ts
src/script/services/congrats.ts
src/script/services/publish/android-publish.ts
src/script/services/publish/index.ts
src/script/services/publish/ios-publish.ts
src/script/services/publish/web-publish.ts
src/script/services/publish/windows-publish.ts
src/script/utils/environment.ts

- Fixes validation error where invalid form elements wouldn't be highlighted when accordion is not expanded. 
- App names can contain spaces
- Refactored form so that result is WindowsPackageOptions, rather than the untyped HTMLFormElement.
- Adds back iOS URL that was accidentally removed
Bugfix

Fixed several issues with Windows package form

---

src/script/pages/app-publish.ts
src/script/pages/portals-publish.ts

Fixes #2269 where the portals publish page platform icons weren't sized correctly.
Bugfix

Fixes #2269, oversized icons on portals publish page

---

src/script/pages/portals-publish.ts

Other
The iOS card was showing up on the portals page.
After talking to the portals team, they wanted the iOS card removed. This PR removes the iOS card.

chore(): remove iOS from portals page

---

src/script/services/app-info.ts

Fixes #2281 
Bugfix
We were requiring users to have a maskable icon because of a bad check. A maskable icon, while highly recommended, is not required for either in-browser installation or in-store installation. Becauase of the way this `if` check worked,  it would return false for the icon check if the user did not have a maskable icon, however this check is only concerned with if they have a 512x512 icon at all.
Updated if check to avoid falling into the trap mentioned above.
- [x ] Ensure that your contribution follows [standard accessibility guidelines](https://docs.microsoft.com/en-us/microsoft-edge/accessibility/design). Use tools …

fix(): fixes #2281

---

src/script/components/content-header.ts
src/script/pages/app-home.ts
src/script/pages/app-index.ts

Header and main body rearranged to have landmark flow

---

src/locales/en_US.json
src/script/utils/url.ts

https://github.com/pwa-builder/PWABuilder/issues/2278
Bugfix
IP Addresses cause the site to hang when validating the URL and fetch things like the manifest or service worker.
We have decided that IP addresses are not going to be supported as valid URLs on PWABuilder. I changed our isValidURL function to remove the regex that accepted IP addresses.
Tested the following URLs passed/failed the isValidURL test as expected. Understand that there are special cases that still cause problems with this way of validating URLs in this way, but these cases existed before I made this change as well. Some were tested without https just to be sure.
192.168.1.1.1 // fail
https://192.168.1.1 //fail
www.asdasd // special pass 
chicken asdkajsd // fail
twitter.com // pass
3.67.42.118 // fail …

IP Address are now Invalid in the URL box on our home page.

---

package.json
rollup.config.dev.js
rollup.config.js

process.env.NODE_ENV defined in build for dev and prod

---

src/script/pages/app-home.ts

Removes survey banner.
Other: Banner was on a schedule, just removing it.
Banner Shows
Banner doesn't show. Code saved in components/survery-banner.ts

PR for removal of the survey banner. Scheduled for the new year.

---

src/script/components/android-form.ts
src/script/components/app-modal.ts
src/script/pages/app-publish.ts

Just adding a tooltip for more clarity on what "other stores" does.
Feature
No description on what "other stores" means or what happens when you generate a package on that tab.
A tooltip has been added to give some explanation to what "other stores" means.

tooltip for other stores

---

src/script/components/manifest-options.ts

deleting one image does not delete all images

---

src/script/utils/environment.ts

Changed windows packaging URL

---

package-lock.json
src/script/services/icon_generator.ts
src/script/utils/interfaces.ts

2nd time uploading updates icon

---

src/script/utils/environment.ts

#2322 
Feature
New VM allows auto deployment of windows packaging service

Changed URL for Windows packaging

---

src/script/utils/win-validation.ts

classic app validation add

---

src/script/components/manifest-options.ts

File validation error add. Large images can be added just needs correct file type

---

.github/fabricbot.json

- Build or CI related changes
Added config file to configure the bot on the repo

Added fabric bot configuration

---

rollup.config.dev.js
rollup.config.js
src/script/components/discord-box.ts
src/script/components/manifest-options.ts
src/script/components/rating-dial.ts
src/script/services/app-info.ts
src/script/services/manifest.ts
src/script/utils/download.ts

https://github.com/pwa-builder/PWABuilder/issues/2636
Bugfix
Lots of warnings when running npm run build
No warnings when running npm run build

removed all build warnings

---

src/script/components/app-sidebar.ts
styles/global.css

#2602 
Bugfix
Color contrast issues in side bar
Issues fixed

Report card color contrast fix

---

src/script/components/app-header.ts
src/script/components/community-hub.ts
src/script/components/companies-packaged.ts
src/script/components/discord-box.ts
src/script/components/success-stories.ts
src/script/pages/app-home.ts

- centering on large screens
- unhid links from header on smaller screens
- added demo url link to smaller screens
- made default link color for discord box black
- made url box full length on smaller screens
- changed hover behavior on start button

Updated changes

---

src/script/utils/win-validation.ts

Modified windows version check

---

src/script/components/android-form.ts
src/script/components/ios-form.ts
src/script/components/loading-button.ts
src/script/components/manifest-options.ts
src/script/components/report-card.ts
src/script/components/sw-picker.ts
src/script/components/windows-form.ts
src/script/pages/app-congrats.ts
src/script/pages/app-home.ts
src/script/pages/app-publish.ts
src/script/pages/portals-publish.ts

#2607 
Bugfix 
Having a button inside of a button causes nested control issues
Button nested from a button

Windows ios android nested control issues

---

src/script/components/oculus-form.ts
src/script/utils/environment.ts

Changed oculus URL to point to docker app

---

src/script/pages/app-home.ts

Bugfix 
The ending slash was causing images to not load for the starter repo
Removed the ending slash

fix(): remove ending slash in link

---

package-lock.json
src/script/components/app-header.ts
src/script/pages/app-home.ts
src/script/services/manifest.ts
src/script/utils/interfaces.ts

Bugfix
1. Header goes back instead of home
2. When you do two urls which should both be store ready in the same session, the second one doesn't make it to the publish page
1. Header goes home
2. URLs that should make it to the publish page make it.

fixed header button to go home, fixed base package issue with two urls

---

src/script/components/windows-form.ts

fixes #2727 
Feature 
When you package for the windows store, there's now an additional option to package for surface hub.

Surface hub support

---

apps/pwabuilder/src/script/pages/app-home.ts

#2906 
Bugfix
After deleting the valid url the start button is still abled
When text in the input field is deleted the start button returns to disabled state

Deleting url disables start button

---

apps/pwabuilder/index.html

Bugfix 
Unregisters any existing service worker registrations

fix(): unregister sw

---

apps/pwabuilder/src/script/components/info-card.ts

#2886
Learn more is currently too vague for a user using a screen reader.
The learn more link is specified to correlating doc topic

More descriptive learn more links

---

apps/pwabuilder/src/script/components/app-footer.ts

#2890
Github, Youtube, and Twitter links in the footer do not describe their purpose in screen reader
Call to action description added

More detailed description for Github, Twitter, and Youtube in footer

---

libraries/manifest-validation/.gitignore
libraries/manifest-validation/README.md
libraries/manifest-validation/package-lock.json
libraries/manifest-validation/package.json
libraries/manifest-validation/src/index.ts
libraries/manifest-validation/src/interfaces.ts
libraries/manifest-validation/src/utils/validation-utils.ts
libraries/manifest-validation/src/validations.ts
libraries/manifest-validation/tsconfig.json

fixes https://github.com/pwa-builder/PWABuilder/issues/2873
Other... : Monorepo related
Made sure that building and stuff still worked. This is super simple and nice!

chore(): add manifest validation lib

---

apps/pwabuilder/src/script/pages/app-publish.ts

I just missed this one button before. Added the analytic call on to it.

[PWABuilder] Added analytics for the Windows test package button

---

apps/pwabuilder/src/script/components/success-stories.ts

#2891
Screen reader doesn't specify which success story is being read (press [Wins + CTRL + Enter] to test)
Screen reader provides a short description to tell which story is being told

Aria label added to specify the success story

---

apps/pwabuilder/src/script/pages/app-home.ts

[#2905](https://github.com/pwa-builder/PWABuilder/issues/2905)
h2 tags used around links which may be confusing to the user
Displayed as links

Incorrect use of h2 tags made into links

---

apps/pwabuilder/src/script/components/community-card.ts
apps/pwabuilder/src/script/components/community-hub.ts
apps/pwabuilder/src/script/components/discord-box.ts
apps/pwabuilder/src/script/pages/app-home.ts

[#2890](https://github.com/pwa-builder/PWABuilder/issues/2890)
Discord link is not descriptive 
Discord link is more descriptive

Descriptive discord link

---

apps/pwabuilder/src/script/components/community-hub-cards.ts

[#2886](https://github.com/pwa-builder/PWABuilder/issues/2886)
Follow now and join now under Join Our Community offer no context of purpose
Follow now and join now under Join Our Community are more descriptive

Community call to action links neet to be more descriptive

---

docs/builder/iOS.md

fixes #2972
Feature
Docs were inconsistent with nextsteps.md.
Now we have one source of truth.

ios Docs Update

---

apps/pwabuilder/src/script/pages/app-report.ts
apps/pwabuilder/src/script/pages/app-testing.ts

[#2911](https://github.com/pwa-builder/PWABuilder/issues/2911)
User was not updated on what was happing during the testing phase after hitting start
The status of the testing phase is announced

Screen reader annouces progress on testing page

---

apps/pwabuilder/src/script/pages/app-publish.ts
apps/pwabuilder/src/script/utils/css/fast-elements.ts

"Test Package" Button styling got overwritten when we merged from main. Added those styles back.

Small change that got overwritten by merge from main

---

apps/pwabuilder/src/script/components/success-card.ts
apps/pwabuilder/src/script/components/success-stories.ts

[#2891](https://github.com/pwa-builder/PWABuilder/issues/2891)
title is not described first
Title is describe before card is read

Short summary of success story added

---

docs/release-notes/2022.md

Updated change notes for 1.0.4 of PWA Studio

docs(): v1.0.4 release notes

---

libraries/manifest-validation/src/interfaces.ts
libraries/manifest-validation/src/validations.ts

These strings will show on the manifest details drop down.

added display strings to manifest validation lib

---

libraries/manifest-validation/package.json
libraries/manifest-validation/src/index.ts
libraries/manifest-validation/src/interfaces.ts
libraries/manifest-validation/src/utils/validation-utils.ts
libraries/manifest-validation/test/validation-tests.js
libraries/manifest-validation/tsconfig.test.json

Other... Please describe: unit tests
no unit tests
We now have unit tests! lol

Mani valid/unit test

---

docs/builder/windows.md

Added icon generation note to Windows article

---

docs/starter/quick-start.md
docs/starter/service-worker.md

3078 Fix Minor issues in PWA Starter docs

---

libraries/manifest-validation/README.md
libraries/manifest-validation/src/index.ts
libraries/manifest-validation/src/utils/validation-utils.ts
libraries/manifest-validation/test/validation-tests.js
libraries/manifest-validation/tsconfig.json

fixes #3080 
Feature
New method: reportMissing
this method reports all of the missing possible fields in a manifest

[mani-validation]: Find missing fields

---

apps/pwabuilder/src/script/components/report-card.ts
apps/pwabuilder/src/script/pages/app-home.ts
apps/pwabuilder/src/script/pages/app-report.ts

In a series of bad merges somehow the new report card page made it on to main. I am not sure why this happened and @jgw96 has been helping me out a lot to fix that bad merge. I think because of an error with the build, it never made it to www.pwabuilder.com because the action would fail. 
I am replacing the new report card page on main with the old one (which is what it should be).
@nmetulev I think since you're looking at general repo stuff this note would be for you. But there really needs to be more strict rules on pushing to main.

Fixing the report card page

---

docs/index.html

Add image that shows in link preview when docs are shared.

Add preview image to docs link

---

apps/pwabuilder/src/script/components/android-form.ts
apps/pwabuilder/src/script/pages/app-publish.ts

Currently the Unsigned Android APK logic doesn't look like its working 100%. This PR addresses that issue and attempts to fix it.

Unsigned APK Logic

---

apps/pwabuilder/src/script/components/android-form.ts
apps/pwabuilder/src/script/pages/app-publish.ts

Trying to debug unsigned package issue isolated to production. Added some logs to track whats happening.

adding logging to track whats going on in production

---

docs/index.html
docs/manifest.json

fixes #3125 
Added basic web manifest.
Will add more capabilities in future pull.

Turned Docsify site into PWA

---

libraries/manifest-validation/src/index.ts
libraries/manifest-validation/src/utils/validation-utils.ts
libraries/manifest-validation/src/validations.ts
libraries/manifest-validation/test/validation-tests.js

Bugfix
Some API changes had been made while I was on vacay, but the tests were not updated.
Tests are now updated.

fix(mani-validation): updated tests to match api changes

---

libraries/manifest-validation/src/validations.ts

Feature 
Adds tests for:
- https://github.com/pwa-builder/PWABuilder/issues/2396
- https://github.com/pwa-builder/PWABuilder/issues/2402

More test updates

---

docs/starter/publish.md
docs/starter/quick-start.md

Documentation content changes 
New docs for the Azure Static Web Apps CLI feature added to the starter in this PR https://github.com/pwa-builder/pwa-starter/pull/75. We should merge these together at around the same time

docs(starter): update on static web apps CLI

---

docs/starter/publish.md

Minor edits to the SWA CLI publishing article.

[DOCS] SWA publish edits

---

apps/pwabuilder-vscode/package.json
apps/pwabuilder-vscode/snippets/pwa-windows.js.code-snippets
apps/pwabuilder-vscode/src/extension.ts
apps/pwabuilder-vscode/src/services/package/package-app.ts
apps/pwabuilder-vscode/src/services/web-publish.ts
apps/pwabuilder-vscode/src/views/publish-checklist.ts

Moving latest code from older repo as we move to the mono-repo. Note, these changes are in-progress changes

[vscode] latest updates

---

apps/blog/src/docs/windows/windows-store-documentation/windows-store-documentation.md
apps/blog/staticwebapp.config.json

fixes #3008 
Other changes:
Removed dead link from blog post.

#3008 - Add Redirects from old Blog Docs to new docs

---

apps/pwabuilder/src/script/pages/app-publish.ts

fixes: no linked issue
Bugfix
Currently we don't collect data about what packages get downloaded after generation
Now we go all the way to the end and collect download information per platform.
@joshsach the new tags are `download-{packageType}-platform` and `download-{packageType}-platform-stopped`

[SITE] extended our current analytics process

---

apps/pwabuilder/src/script/pages/app-publish.ts
apps/pwabuilder/src/script/services/publish/index.ts

Other android and android will appear in their own funnels in analytics

split other android and android for analytics

---

apps/pwabuilder/src/script/components/android-form.ts
apps/pwabuilder/src/script/components/publish-pane.ts
apps/pwabuilder/src/script/components/windows-form.ts
apps/pwabuilder/styles/form-styles.css

floating generation button

---

docs/builder/faq.md

@Jaylyn-Barbee added that error

Added common error for empty icons array

---

docs/_sidebar.md
docs/builder/android.md
docs/builder/app-store.md
docs/builder/meta.md
docs/builder/windows.md

Fixes #3257 
Added CTA's to the end of each packaging article to point out other platforms to package PWA's for.

Added CTA's to the end of each packaging section

---

apps/pwabuilder/index.html

fixes #3276 
Bugfix
There were compliance issues
I fixed it using the recommended solution in the issue.

ion icons compliant now

---

apps/pwabuilder/src/script/components/android-form.ts
apps/pwabuilder/src/script/components/ios-form.ts
apps/pwabuilder/src/script/components/oculus-form.ts
apps/pwabuilder/src/script/components/windows-form.ts

[#2690](https://github.com/pwa-builder/PWABuilder/issues/2690)
Bugfix 
Special character "|" should not be acceptable for app name

| character should not be acceptable for app name

---

apps/pwabuilder-vscode/package.json

Need to change supported versions so that users can install the pre-release version. This will not cause problems for our existing users.

chore(): update supported VSCode versions

---

apps/pwabuilder-vscode/src/services/new-pwa-starter.ts

fixes #3313 
Other... Please describe: UX Update
New generated app would open in its own workspace
New generated app now opens in its own VSCode window.

fix(vscode): fixes https://github.com/pwa-builder/PWABuilder/issues/3313

---

docs/README.md
docs/_sidebar.md
docs/release-notes/2022.md
docs/starter/quick-start.md
docs/studio/create-new.md
docs/studio/existing-app.md
docs/studio/faq.md
docs/studio/package.md
docs/studio/quick-start.md
docs/studio/snippets.md

Update the changelog for the next Studio release

docs(vscode): update changelog for upcoming Studio release

---

docs/starter/quick-start.md

Fix broken link on starter quick start

---

apps/pwabuilder-vscode/src/library/package-utils.ts
apps/pwabuilder-vscode/src/services/manifest/manifest-service.ts

fixes #3317
Bugfix
Manifest link was not being added.
Manifest link is now added.

fix(vscode): manifest index link gets added

---

docs/builder/windows.md

fixes #3333 
Just added links + warnings about partner center requirement for windows packaging.

Fixes #3333 - Added more notices about partner center to windows packaging

---

components/manifest-previewer/src/screens/categories-screen.ts

fixes #2460 
Bugfix 
Added ellipsis on last line of category description in manifest previewer

Manifest previewer ellipsis add

---

apps/pwabuilder-vscode/src/services/package/package-app.ts
apps/pwabuilder-vscode/src/services/package/package-view.ts

fixes #3366 
Bugfix
SW detection code was not working for the package checklist panel, and was also causing issues with packaging.
Re-use the same SW detection code in these places instead of just trying to grab the worker.

[VSCODE]: Service Worker detection fix

---

apps/pwabuilder/index.html
apps/pwabuilder/package-lock.json
apps/pwabuilder/src/script/components/todo-list-item.ts
components/manifest-editor/index.html
components/manifest-editor/package-lock.json
components/manifest-editor/src/components/manifest-info-form.ts

- Color Picker updated in ME
- Todo items more aligned? Can't tell its tricky?

First batch of feedback coming through

---

docs/starter/faq.md

Two words in the starter FAQ were mispelled (`barnd` & `reeady`).
The words are now spelled correctly (`brand` & `ready`).
Didn't think it was necessary to open an issue to fix 2 typos :)

Fix typos in starter FAQ

---

apps/pwabuilder/src/script/pages/app-publish.ts

fixes #3370 
Bugfix 
Test package downloads empty zip file
Uses the same download function as icons, somehow that works on google chrome desktop

Fixes download issue on google chrome

---

apps/pwabuilder/src/script/pages/app-home.ts
apps/pwabuilder/src/script/pages/app-report.ts
apps/pwabuilder/styles/global.css
components/manifest-editor/src/components/manifest-icons-form.ts
components/manifest-editor/src/components/manifest-info-form.ts
components/manifest-editor/src/components/manifest-platform-form.ts
components/manifest-editor/src/components/manifest-settings-form.ts
components/manifest-editor/src/components/pwa-manifest-editor.ts
libraries/manifest-validation/src/validations.ts

- #3388 
- Color picker moving slow
- #3399 
- #3396
- #3394 
- #3395
- #3387 
- #3398 
- #3379
- #3382

Taking in some of the feedback, listed below.

---

apps/pwabuilder/src/script/components/app-header.ts
apps/pwabuilder/src/script/components/manifest-editor-frame.ts
apps/pwabuilder/src/script/components/sw-selector.ts
apps/pwabuilder/src/script/pages/app-report.ts
components/manifest-editor/src/components/manifest-platform-form.ts

- #3410 
- #3414 
- #3406 
- #3407

Another set of fixes

---

apps/pwabuilder/src/script/components/app-modal.ts
apps/pwabuilder/src/script/pages/app-publish.ts

fixes #3334
janky way to plug this link in there - but didn't want to refactor `app-modal` with the redesign coming so soon.

3334 add docs link to windows packaging

---

apps/pwabuilder/src/script/components/summit-banner.ts
docs/index.html

Quick summit banner text update on docs + site.

Update pwa summit banner text

---

apps/pwabuilder/src/script/components/publish-pane.ts
apps/pwabuilder/src/script/components/todo-list-item.ts

The text would break on pagination in the list. This push fixes that.

fixed small pagination issue

---

apps/pwabuilder-chromium-extension/package-lock.json
apps/pwabuilder-chromium-extension/package.json
apps/pwabuilder-chromium-extension/src/components/scanner.ts
apps/pwabuilder-chromium-extension/src/index.ts
apps/pwabuilder-chromium-extension/src/utils/manifest.ts
apps/pwabuilder-chromium-extension/tsconfig.json
libraries/manifest-validation/src/index.ts

[edge-extension] Updated extension deps

---

apps/pwabuilder-chromium-extension/package.json
apps/pwabuilder-chromium-extension/webpack.config.js
components/manifest-editor/src/components/manifest-info-form.ts
components/manifest-editor/src/components/manifest-platform-form.ts
components/manifest-editor/src/components/manifest-screenshots-form.ts
components/manifest-editor/src/components/manifest-settings-form.ts
components/manifest-editor/src/components/pwa-manifest-editor.ts

Bugfix
Component, when used standalone, was not rendering correctly as some Shoelace components were not being loaded.
The component now imports all of the shoelace components it uses, guaranteeing it renders correctly when used standalone from the site.

Mani editor

---

apps/pwabuilder/src/script/components/app-header.ts
apps/pwabuilder/src/script/components/publish-pane.ts
apps/pwabuilder/src/script/pages/app-report.ts

Fixes issues below

---

apps/pwabuilder/src/script/services/tests/service-worker.ts

Removed lighthouse check

---

apps/pwabuilder/src/script/components/manifest-editor-frame.ts
apps/pwabuilder/src/script/pages/app-report.ts
apps/pwabuilder/src/script/services/tests/security.ts
apps/pwabuilder/src/script/services/tests/service-worker.ts
components/manifest-editor/src/components/manifest-screenshots-form.ts
components/manifest-editor/src/components/pwa-manifest-editor.ts

- #3479 
- Made chevrons into buttons so you can tab to them for pagination
- Added the base url to the input box for generating screenshots so the user doesn't have to retype it

Fixes below Issues

---

apps/pwabuilder/src/script/components/sw-selector.ts
apps/pwabuilder/src/script/pages/app-home.ts
apps/pwabuilder/src/script/pages/app-report.ts
components/manifest-editor/src/components/manifest-platform-form.ts
components/manifest-editor/src/components/manifest-settings-form.ts

- Some design nitpicks
- #3507 
- #3434 
- A small design issue on the home page.

New changes

---

apps/pwabuilder/src/script/components/app-footer.ts

fixes #3355 
Bugfix 
More specific tooltip added to social media links

Tooltip specific description for footer icons

---

apps/pwabuilder/src/script/components/app-footer.ts
apps/pwabuilder/src/script/components/companies-packaged.ts

fixes #3373 
Bugfix
More descriptive pause and play label add

Ada descriptive pause button

---

apps/pwabuilder/src/script/components/app-footer.ts
apps/pwabuilder/src/script/components/community-card.ts
apps/pwabuilder/src/script/components/companies-packaged.ts
apps/pwabuilder/src/script/components/info-card.ts
apps/pwabuilder/src/script/components/success-card.ts
apps/pwabuilder/src/script/pages/app-home.ts

fixes #3375 
Bugfix 
Header tag on success cards should be smaller than main header of the section

Ada header tag fix

---

apps/pwabuilder/src/script/components/app-footer.ts
apps/pwabuilder/src/script/components/community-card.ts
apps/pwabuilder/src/script/components/companies-packaged.ts
apps/pwabuilder/src/script/components/info-card.ts
apps/pwabuilder/src/script/components/success-card.ts
apps/pwabuilder/src/script/pages/app-home.ts

fixes #3376 
Bugfix
Icons in footer still visible on hover/focus in high contrast mode

Ada footer icon contrast fix

---

apps/pwabuilder/src/script/components/app-footer.ts
apps/pwabuilder/src/script/components/community-card.ts
apps/pwabuilder/src/script/components/companies-packaged.ts
apps/pwabuilder/src/script/components/info-card.ts
apps/pwabuilder/src/script/components/success-card.ts
apps/pwabuilder/src/script/pages/app-home.ts

fixes #3377 
Bugfix 
Border on keyboard focus visible on high contrast mode

Ada keyboard focus fix

---

apps/pwabuilder/src/app-index.ts
apps/pwabuilder/src/script/components/manifest-editor-frame.ts
apps/pwabuilder/src/script/components/publish-pane.ts
apps/pwabuilder/src/script/components/sw-selector.ts
apps/pwabuilder/src/script/pages/app-report.ts
components/manifest-editor/src/components/manifest-icons-form.ts
components/manifest-editor/src/components/manifest-info-form.ts
components/manifest-editor/src/components/manifest-platform-form.ts
components/manifest-editor/src/components/manifest-screenshots-form.ts
components/manifest-editor/src/components/manifest-settings-form.ts
components/manifest-editor/src/components/pwa-manifest-editor.ts

- Design Changes for modals
- #3518

Last changes before merge

---

docs/release-notes/2022.md

Release notes for updates to packaging flow and new report card page.

Redesign Release Notes - October 6th

---

apps/pwabuilder/src/app-index.ts
apps/pwabuilder/src/script/components/publish-pane.ts
apps/pwabuilder/src/script/pages/powerplatform-publish.ts
apps/pwabuilder/src/script/services/manifest.ts

This PR restores the portals page used by the Power Platform team

Added portals page

---

apps/pwabuilder/src/script/components/publish-pane.ts
components/manifest-editor/src/components/manifest-screenshots-form.ts

fixes #3566
Feature
No feedback for successful downloads.

added feedback for successful downloads

---

apps/pwabuilder/src/script/pages/app-report.ts

Just adding comments and cleaning up the code.

Reorganized the CSS and Commented each function with its purpose

---

docs/_sidebar.md
docs/builder/manifest.md

#3551: pwabuilder manifest documentation

---

apps/pwabuilder/src/script/components/cookie-banner.ts
apps/pwabuilder/src/script/pages/image-generator.ts
components/manifest-editor/src/components/manifest-icons-form.ts
components/manifest-editor/src/components/manifest-info-form.ts
components/manifest-editor/src/components/manifest-platform-form.ts
components/manifest-editor/src/components/manifest-screenshots-form.ts
components/manifest-editor/src/components/manifest-settings-form.ts

- fixed cookies banner
- fixed spacing of (i) in ME
- fixed text color issue on /imageGenerator

More small tweaks from convos with Sana

---

.github/workflows/pwabuilder-main.yml
.github/workflows/pwabuilder-preview.yml

Added new paths in github actions file so the workflow runs for changes in the libraries.

Update paths for github actions to include libraries

---

apps/blog/src/includes/layouts/basedoc.njk
apps/blog/src/includes/layouts/basepost.njk
apps/pwabuilder/index.html
docs/index.html

Bugfix 
Wrong MIME `image/x-icon` for `.png`.
Correct MIME  `image/png`.
nope

Fix MIME for PNG image

---

apps/pwabuilder-vscode/src/manifest-utils.ts
apps/pwabuilder-vscode/src/services/manifest/mani-suggestions.ts
apps/pwabuilder-vscode/src/services/validation/sw-view.ts
apps/pwabuilder-vscode/src/services/validation/validation.ts
apps/pwabuilder/src/script/components/android-form.ts
components/manifest-editor/src/components/manifest-icons-form.ts
components/manifest-editor/src/components/manifest-info-form.ts
components/manifest-editor/src/components/manifest-platform-form.ts
components/manifest-editor/src/components/manifest-screenshots-form.ts
components/manifest-editor/src/components/manifest-settings-form.ts
libraries/manifest-validation/src/validations.ts

Updated manifest links from external to pwabuilder docs

---

apps/pwabuilder/src/script/utils/environment.ts

Update android service to point to a different slot

---

libraries/manifest-validation/src/index.ts
libraries/manifest-validation/src/validations.ts
libraries/manifest-validation/test/validation-tests.js

Reverts pwa-builder/PWABuilder#3677

Revert "fix(validation): shortcuts are validated for minimum icon size"

---

docs/README.md
docs/styles/global.css

fixes #3336 
Added three cards for each tool to PWA docs homepage to make navigating to desired documentation easier.

Added clearer tooling navigation to docs homepage

---

apps/pwabuilder-vscode/src/services/manifest/manifest-service.ts

fixes #3697
Bugfix
Manifest snippet was generating prefer_related_applications as a string instead of Boolean because of a misunderstanding of mine on the snippet syntax.
prefer_related_applications is now generated as a boolean.

fix(studio): fixes https://github.com/pwa-builder/PWABuilder/issues/3697

---

apps/pwabuilder/src/script/components/share-card.ts

Fixes for share card mobile

---

docs/manifest.json

No associated issue.
Quick fix from something I forgot to do a while back. Added rest of shortcuts to documentation PWA demo.

Added the rest of the shortcuts to docs PWA

---

apps/pwabuilder/src/script/components/share-card.ts
apps/pwabuilder/src/script/pages/app-report.ts

Debugging html to image on safari

debugging safari for share card

---

apps/pwabuilder/package-lock.json
apps/pwabuilder/package.json
apps/pwabuilder/src/script/components/app-footer.ts
apps/pwabuilder/src/script/components/app-package-form-base.ts
apps/pwabuilder/src/script/components/community-card.ts
apps/pwabuilder/src/script/components/community-hub.ts
apps/pwabuilder/src/script/components/companies-packaged.ts
apps/pwabuilder/src/script/components/cookie-banner.ts
apps/pwabuilder/src/script/components/info-card.ts
apps/pwabuilder/src/script/components/info-circle-tooltip.ts
apps/pwabuilder/src/script/components/publish-pane.ts
apps/pwabuilder/src/script/components/resource-hub.ts
apps/pwabuilder/src/script/components/success-card.ts
apps/pwabuilder/src/script/pages/app-home.ts
apps/pwabuilder/src/script/pages/app-report.ts
components/manifest-editor/src/components/manifest-icons-form.ts
components/manifest-editor/src/components/manifest-info-form.ts
components/manifest-editor/src/components/manifest-platform-form.ts
components/manifest-editor/src/components/manifest-screenshots-form.ts
components/manifest-editor/src/components/manifest-settings-form.ts

Made sure all "black" text was our special font color
fixed some error css in the manifest editor
fixed some accent colors on buttons
standardized text capitalization 
standardized all links to be arrow links

CSS changes

---

docs/home/pwa-intro.md
docs/home/sw-intro.md

fixes #3552 
Added security section to Service Worker docs and added an extra note for clarity in PWA overview.

[DOCS] Added more guidance on security to service worker docs

---

apps/pwabuilder-vscode/src/extension.ts
apps/pwabuilder-vscode/src/services/usage-analytics.ts

chore(): put file back to correct state before merge

---

docs/builder/manifest.md

fixes #3755
Added docs on icon validations to PWABuilde/Manifest Options page.

[DOCS] #3755: Icon Validation Guidance

---

libraries/manifest-validation/src/validations.ts

fixes #3778
Bugfix
Internal structure of related_applications was not validated.
Now validated.

fix(mani-validation): related_applications internals are validated

---

libraries/manifest-validation/src/validations.ts

fix(): roll back relativity check for now

---

docs/sw.js

fixes #3799
Old caching behavior:
SW creates a race condition between network content and cached response and updates cache in background. Cache always wins out, resulting in stale content being served when visiting the site for the first time since an update.
New behavior:
Added a delay on serving the cached response from the race. If the network responds quickly, the updated content will be served immediately, otherwise we go to the cache after the network requests times out. Cached content is still updated in the background.

[STARTER] Updated docs service worker to prioritize network content

---

apps/pwabuilder/src/script/components/windows-form.ts
components/manifest-editor/src/components/manifest-info-form.ts
components/manifest-editor/src/components/manifest-platform-form.ts
components/manifest-editor/src/components/manifest-settings-form.ts

fixes #3806
Bugfix
Described here https://github.com/shoelace-style/shoelace/discussions/1185
Thanks to Cory from shoelace

Fixed blue focus-within state for sl-menu-items

---

docs/starter/publish.md

[DOCS] Updated Docs on Github Pages deploy for Starter

---

docs/builder/faq.md

Same words were repeated twice.
Repeated words have been erased.

fix: typo in builder faq

---

apps/blog/src/docs/ios/ios-platform/ios-platform.md
components/pwa-auth/docs/creating-apple-key.md
components/pwa-auth/docs/creating-facebook-key.md
components/pwa-auth/docs/creating-google-key.md
components/pwa-auth/docs/creating-microsoft-key.md
docs/builder/faq.md
docs/builder/windows.md
docs/index.html
docs/starter/publish.md

fixes #3872 
All external links should open in new tab now.

[DOC] Fix broken external links

---

docs/builder/windows.md

[DOCS] Add note about full trust warning to Microsoft PWABuilder Docs

---

docs/_sidebar.md
docs/builder/asset-links-faq.md
docs/builder/faq.md

[DOCS] Update asset links guidance location

---

apps/pwabuilder/src/script/components/resource-hub-cards.ts

[DOCS] Updated 'What makes a PWA?' links on homepage to point to documentation

---

docs/home/pwa-intro.md

Documentation content changes 

Fix typo in pwa-intro.md

---

apps/pwabuilder/src/script/components/community-card.ts
apps/pwabuilder/src/script/components/companies-packaged.ts
apps/pwabuilder/src/script/components/info-card.ts

Homepage role attributes fix

---

apps/pwabuilder/src/script/components/share-card.ts

ADA Share pass requests add

---

docs/starter/adding-content.md
docs/starter/tech-overview.md

Current content was pointed at Vaadin router. 
Now updated to point to the new router that both we and Judah are using for his project . Note, should be merged along with https://github.com/pwa-builder/pwa-starter/pull/89

docs[starter]: update docs to match our new router

---

apps/pwabuilder/src/script/components/community-hub.ts

Join our community aria role fix

---

apps/pwabuilder/src/script/components/share-card.ts

Hashtag add to share message

---

docs/builder/manifest.md

added  ***Required member*** to the required members of file handlers

---

.github/workflows/cli-main.yml

Added CLI workflow for npm publish

---

apps/blog/src/assets/css/base.css

high contrast css add

---

apps/blog/src/docs/windows/update-existing-app/update-an-existing-app.md
apps/blog/src/includes/header.njk

Update existing app alt add

---

apps/pwabuilder/package.json
apps/pwabuilder/src/script/components/app-header.ts
apps/pwabuilder/src/script/services/publish/android-publish.ts

Logo- double keyboard focus fix

---

apps/pwabuilder/src/script/pages/app-home.ts
apps/pwabuilder/src/script/services/publish/android-publish.ts

home input field on focus color ratio fix

---

docs/_sidebar.md
docs/release-notes/2023.md

Release notes for new features as expected by the release template: #4013
No release notes for 2023 features
Release notes for 2023 features

[DOCS] Release notes for 2023 features (share and tooltips) added

---

apps/blog/src/docs/windows/what-is-classic-package/what-is-a-classic-package.md

non-interactive items not numbered during VA

---

docs/home/native-features.md

#4095: Added further share target guidance to docs

---

apps/pwabuilder/src/script/pages/app-report.ts

Fixed string - 'You have a one or more fields' to 'You have one or more fields'
Bugfix 
Language Update

Update app-report.ts for updating message

---

apps/pwabuilder/src/script/pages/app-report.ts
components/manifest-editor/src/components/manifest-icons-form.ts
docs/home/native-features.md
docs/home/pwa-workshop.md

fixes #4113
Bugfix
Type errors in console when icons were not in manifest
No errors because we check for icons before running code that involves icons.

Fixed type errors around not having icons in the manifest editor

---

docs/builder/manifest.md

[DOCS] Added manifest docs for id and edge_side_panel members

---

docs/builder/faq.md
docs/builder/quick-start.md

[DOCS] Added clarity about updating to FAQ and to quick start for pwabuilder

---

apps/pwabuilder/src/script/components/publish-pane.ts
apps/pwabuilder/src/script/components/test-publish-pane.ts

Switched from red to purple for experimental tag.

[SITE] Color feedback for Issue 4112: experimental tag bug

---

docs/home/native-features.md

no associated issue, minor typo fix

[DOCS] Typo in Adding Native Features code block

---

docs/builder/manifest.md

No associated issue, just a typo.

[DOCS] Fixed launch_handler manifest docs typo

---

docs/builder/app-store.md

[DOCS] Corrected inaccuracy around adding cert for iOS packaging

---

docs/builder/faq.md

fixes #4141 
@khmyznikov added that recommended guidance to the PWABuilder FAQ - I also added android info in addition to Windows.

[DOCS] 4141: Related applications instruction for Windows and Android

---

.github/workflows/docs-github-pages.yml

Missing `npm i` in action file.

Actions Docs error patch

---

.github/workflows/docs-github-pages.yml

Reverts pwa-builder/PWABuilder#4206

Revert "[DOCS] Another patch for github action"

---

.github/workflows/docs-github-pages.yml

Reverts pwa-builder/PWABuilder#4205

Revert "Actions Docs error patch"

---

.github/workflows/docs-github-pages.yml
docs/package.json

@jgw96 This should work, but lets keep our eyes open for next merge to main just in case.

[DOCS] Remove broken symlink to allow for custom artifact upload

---

apps/pwabuilder/src/script/pages/qualification/app-token.ts
apps/pwabuilder/src/script/pages/qualification/token-congratulations.ts

end of campaign reclaim

---

apps/pwabuilder/src/script/services/auth_service.ts

Changed authority URL

---

apps/pwabuilder/src/script/components/windows-form.ts

Done pending tooltip text and link from Lena.

Adding AI Hub link to Windows Packaging form

---

apps/pwabuilder/src/script/components/publish-pane.ts
apps/pwabuilder/src/script/pages/image-generator.ts
docs/README.md
docs/home/pwa-intro.md
docs/home/sw-intro.md
docs/styles/global.css

fixes https://github.com/pwa-builder/PWABuilder/issues/4230
Bugfix
See issue
Hierarchy fixed on all urls linked in the original issue

[Accessibility] fixed header hierarchy issues

---

apps/pwabuilder/src/script/pages/image-generator.ts

fixes https://github.com/pwa-builder/PWABuilder/issues/4231
Bugfix
Radios and Checkboxes not associated with their labels
Radios and Checkboxes explicitly link to the labels.
Need to double check that I interpreted and resolved the issue correctly.

[Accessibility] Fix to radios and checkboxes not being associated with their labels

---

apps/pwabuilder/src/script/pages/app-report.ts

fixes #4254 and #4233
Bugfix 
1. Buttons didn't have a name or label
2. Buttons didn't have audio feedback when clicked and using narrator
1. Buttons named 
2. Buttons announce the page number when clicked in narrator.

[Accessibility] Updates to the action items prev and next buttons

---

docs/src/menuData.ts
docs/starter/cli-usage.md
docs/starter/quick-start.md

Updated PWA Starter quick start to use CLI and added a CLI usage page.

[CLI] Documentation update for CLI release

---

apps/blog/src/includes/layouts/basedoc.njk
apps/blog/src/posts/announcing-cli/announcing-cli.md
apps/pwabuilder/index.html
docs/index.html

[SEO] 4394: Google Search Console verification tags

---

docs/index.html
docs/styles/vs-prism.css

fixes #4276 
Added VS code-based theme w better contrast for code snippets.

[DOCS][ACCESIBILITY] 4276: Code Snippet contrast

---

docs/starter/service-worker.md

fixes #4424 
wrong link
right link
I'm on mobile, can't do the checklist or fix the end of file diff

Update service-worker docs link

---

docs/builder/manifest.md
docs/home/benefits-of-pwa.md
docs/home/native-features.md
docs/home/pwa-intro.md
docs/release-notes/2023.md
docs/src/menuData.ts

[DOCS] Update docs for app capabilities and add release notes

---

apps/blog/src/includes/sub-header.njk

Reverts pwa-builder/PWABuilder#4518

Revert "Bethpan/blog"

---

apps/blog/src/includes/sub-header.njk

add back button to tag page

---

apps/pwabuilder/src/script/components/app-header.ts

Updated header to the designs we agreed upon for the uniform header work that Sana has been doing.

[HOTFIX] Updated header for staging

---

.github/workflows/blog-preview.yml

Create action file for blog staging deploy

---

apps/pwabuilder/src/script/utils/environment.ts

Replaced staging URL for windows packaging with new docker URL

---

.github/workflows/pwabuilder-main.yml

Added node_env in production workflow
fixes #[issue number]

Update pwabuilder-main.yml with node_env

---

docs/home/pwa-intro.md

hotfix for dead link pointed out in discord @khmyznikov

Fix dead link in pwa-intro

---

apps/blog/src/posts/goodnotes-showcase/goodnotes-showcase.md

Added data for author profile section in Justins new blog.

Adding author profile to the new blog

---

apps/pwabuilder/src/script/pages/app-report.ts

#4614:  Report card button fix

---

apps/blog/src/includes/author-profile.njk

Center text in Blog Author Profiles

---

apps/pwabuilder/src/script/components/app-footer.ts

fixes #4631 
Other... : Compliance
New link in our footer

new footer link for compliance

---

apps/pwabuilder/src/script/components/discord-box.ts
apps/pwabuilder/src/script/components/share-card.ts
docs/builder/android.md

Fixed:
#4259 
#4744
Half of #4749: For the search bar clear button, that comes from an external component we have no control over.

Fixing various accessbility bugs

---

apps/pwabuilder/src/script/utils/environment.ts

fixes https://github.com/pwa-builder/PWABuilder/issues/4823
Bugfix
Service was broken, unfortunately I must be light on details here.
Pointing to our new instance of the main test service.

update to new service instance

---

apps/pwabuilder/src/script/services/publish/windows-publish.ts

Reverts pwa-builder/PWABuilder#4852

Revert "fix(): temp fix for packaging as we work through backend issues"

---

docs/builder/app-store.md

fixes #4859
iOS docs updated to specify later iOS version.

iOS 17+ update

---

apps/pwabuilder/index.html

Adds Bing site verification
Feature

Adds Bing site verification

---

apps/pwabuilder-chromium-extension/package-lock.json
apps/pwabuilder-chromium-extension/package.json
apps/pwabuilder/package-lock.json
apps/pwabuilder/src/script/components/app-header.ts
components/code-editor/package-lock.json
components/code-editor/package.json
components/code-editor/src/code-editor.ts
components/code-editor/src/utils/codemirror.ts
components/code-editor/src/utils/debounce.ts
components/code-editor/src/utils/events.ts
components/code-editor/src/utils/once.ts
components/code-editor/tsconfig.json
components/manifest-editor/package-lock.json
components/manifest-editor/package.json
components/manifest-previewer/package-lock.json
components/manifest-previewer/package.json
components/pwa-auth/package.json

Makes all our components use a consistent Lit and Shoelace version.
Bugfix

Removes duplicate versions of Shoelace, console logs

---

apps/pwabuilder/index.html
apps/pwabuilder/package-lock.json
apps/pwabuilder/package.json
apps/pwabuilder/public/service-worker.js
apps/pwabuilder/vite.config.ts

Adds workbox-enabled service worker
Feature

Adds service worker

---

apps/pwabuilder/Services/AnalyticsService.cs
apps/pwabuilder/Validations/ManifestValidation.cs
apps/pwabuilder/Validations/Models/Icon.cs
apps/pwabuilder/Validations/Schema/FileHandlerSchema.cs
apps/pwabuilder/Validations/Schema/WidgetsSchema.cs

[backend migration] csharpier format

---

apps/pwabuilder/Controllers/AuditServiceWorkerController.cs
apps/pwabuilder/Controllers/ReportController.cs
apps/pwabuilder/Models/Report.cs
apps/pwabuilder/Models/ServiceWorkerResult.cs
apps/pwabuilder/Services/AnalyticsService.cs
apps/pwabuilder/Services/ImageValidationService.cs
apps/pwabuilder/Services/ServiceWorkerAnalyzer.cs

[backend migration] report and audit api - standardize code

---

docs/builder/windows.md

fixes #4985
Updating the partner center link to https://aka.ms/partnercenterregistration

[Documentation] update microsoft partner center link on Docs

---

.github/workflows/docs-github-pages.yml
docs/builder/app-store.md
docs/builder/faq.md
docs/builder/manifest.md

related 
- #4985
- Build or CI related changes 
Documentation is not deployed due to deprecated actions

[gh actions] update docs gh pages action workflow

---

apps/pwabuilder/Controllers/FindServiceWorkerController.cs
apps/pwabuilder/Controllers/FindWebManifestController.cs
apps/pwabuilder/Services/PuppeteerService.cs

fix api error handler response

---

apps/pwabuilder/Controllers/FindServiceWorkerController.cs
apps/pwabuilder/Controllers/FindWebManifestController.cs

[backend migration] expected controllers output

---

apps/pwabuilder/Controllers/FindServiceWorkerController.cs
apps/pwabuilder/Controllers/FindWebManifestController.cs
apps/pwabuilder/Program.cs

fix error handler in puppeteer flow and allowed cors for development

---

apps/pwabuilder/Services/LighthouseService.cs

[backend migration] add port generation for puppeteer sharp chrome instances

---

Dockerfile.production
apps/pwabuilder/Services/LighthouseService.cs
apps/pwabuilder/Services/PuppeteerService.cs

[backend migration] fix puppetter wait for networkd idle timeout

---

.vscode/launch.json
Dockerfile.production
apps/pwabuilder/Properties/launchSettings.json
apps/pwabuilder/Services/LighthouseService.cs
apps/pwabuilder/Utils/ReportUtils.cs

[backend migration] lighthouse container setup

---

README.md

[backend migration] update readme development section

---

apps/pwabuilder/Utils/ReportUtils.cs

[backend migration] fix audits score type check in report mapper
